Repository continuedev/continue, pull requests merged in 2025-08, with the labels that each got.

#6924 fix: typos in the Contributing Guide
  CONTRIBUTING.md
Labels: lgtm, size:S

#6927 fix: :lipstick: Fix the enter button foreground color
  gui/src/components/ui/Button.tsx
Labels: lgtm, size:XS

#5961 fix: added Process env secret key support
  core/config/yaml/LocalPlatformClient.ts
  core/config/yaml/LocalPlatformClient.vitest.ts
  packages/config-yaml/src/interfaces/SecretResult.ts
Labels: lgtm, size:L

#6835 Update GitHub issue auto-assignment workflow: replace sestinj with tingwai
  .github/workflows/auto-assign-issue.yaml
Labels: lgtm, size:XS

#6914 docs: adds an assistant overview guide
  docs/customize/deep-dives/configuration.mdx
  docs/docs.json
  docs/getting-started/extensions.mdx
  docs/getting-started/overview.mdx
  docs/guides/understanding-assistants.mdx
  docs/images/nextjs-assistant.png
Labels: size:L

#6920 Update source control documentation with file naming and versioning details
  docs/hub/source-control.mdx
Labels: size:XS

#6748 chore: delete unused TransformersJsWorkerThread.js
  core/llm/llms/TransformersJsWorkerThread.js
Labels: size:M

#6816 fix: improve findSearchMatch to fix whitespace matching errors
  core/edit/searchAndReplace/findSearchMatch.strategy.test.ts
  core/edit/searchAndReplace/findSearchMatch.ts
Labels: lgtm, size:XL

#6706 fix: include Editor Content description with request
  gui/src/components/mainInput/TipTapEditor/utils/processEditorContent.test.ts
  gui/src/components/mainInput/TipTapEditor/utils/processEditorContent.ts
Labels: lgtm, size:XS

#6459 refactor: :recycle: Refactor to use a single animated ellipsis component
  gui/src/components/AnimatedEllipsis.tsx
  gui/src/components/StepContainer/ConversationSummary.tsx
  gui/src/components/index.ts
  gui/src/components/mainInput/Lump/LumpToolbar/GeneratingIndicator.tsx
  gui/src/components/mainInput/belowMainInput/ContextItemsPeek.tsx
  gui/src/components/mainInput/belowMainInput/ThinkingBlockPeek.tsx
  gui/src/pages/config/IndexingProgress/IndexingProgressTitleText.tsx
Labels: lgtm, size:M

#6932 feat: :sparkles: MCP Prompts now display when inserted
  core/config/profile/doLoadConfig.ts
  gui/src/redux/selectors/index.ts
Labels: lgtm, size:M

#6501 test: check for required params on tool defs
  core/tools/definitions/index.ts
  core/tools/definitions/toolDefinitions.test.ts
  core/tools/index.ts
Labels: lgtm, size:L

#6818 feat: add tool call support for moonshot models
  core/llm/autodetect.ts
  core/llm/toolSupport.ts
Labels: lgtm, size:M

#6789 chore: use prettierignore when formatting
  .prettierignore
  package.json
Labels: size:S

#6855 Add middle mouse button click handling to close tabs in TabBar component
  gui/src/components/TabBar/TabBar.tsx
Labels: lgtm, size:XS

#6949 docs: Add apiBase to remote instance config and standardize LM Studio page content
  docs/customize/model-providers/more/lmstudio.mdx
Labels: size:M

#6964 fix: don't fail tests for conventional commit check
  .github/workflows/compliance.yaml
Labels: lgtm, size:XS

#6792 fix: spacing between divs on tool calls
  gui/src/components/StepContainer/StepContainer.tsx
  gui/src/components/mainInput/GradientBorder.tsx
Labels: size:S

#6761 docs: correct deep-dives internal links
  docs/customization/mcp-tools.mdx
  docs/hub/blocks/block-types.mdx
Labels: lgtm, size:XS

#6759 fix: register YAML config schema by its URI in VS Code
  extensions/vscode/src/activation/activate.ts
Labels: lgtm, size:XS

#6970 fix: always read file before search and replace
  core/tools/definitions/searchAndReplaceInFile.ts
Labels: lgtm, size:S

#6969 chore: update the issue template to guide folks to github discussions
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/improvement_suggestion.yml
Labels: lgtm, size:M

#6977 chore: bump extension versions
  extensions/intellij/gradle.properties
  extensions/vscode/package.json
Labels: lgtm, size:XS

#7004 fix: jetbrains release action
  .github/workflows/jetbrains-release.yaml
Labels: lgtm, size:XS

#6963 feat: cache model responses for near-instant suggestions
  core/core.ts
  core/nextEdit/NextEditEditableRegionCalculator.ts
  core/nextEdit/NextEditPrefetchQueue.ts
  core/nextEdit/NextEditProvider.ts
  core/nextEdit/NextEditProvider.vitest.ts
  core/nextEdit/constants.ts
  core/nextEdit/diff/diff.ts
  core/nextEdit/templating/NextEditPromptEngine.ts
  core/nextEdit/templating/NextEditPromptEngine.vitest.ts
  core/nextEdit/templating/mercuryCoderNextEdit.ts
  core/nextEdit/templating/mercuryCoderNextEdit.vitest.ts
  core/nextEdit/templating/utils.ts
  core/nextEdit/templating/utils.vitest.ts
  core/nextEdit/types.ts
  core/util/text.ts
  core/util/text.vitest.ts
  extensions/vscode/src/activation/JumpManager.ts
  extensions/vscode/src/activation/JumpManager.vitest.ts
  extensions/vscode/src/activation/NextEditWindowManager.ts
  extensions/vscode/src/activation/SelectionChangeManager.ts
  extensions/vscode/src/activation/SelectionChangeManager.vitest.ts
  extensions/vscode/src/autocomplete/GhostTextAcceptanceTracker.ts
  extensions/vscode/src/autocomplete/completionProvider.ts
  extensions/vscode/src/commands.ts
  extensions/vscode/src/extension/VsCodeExtension.ts
Labels: size:XXL

#6966 docs: Add description to cli.mdx
  docs/guides/cli.mdx
Labels: lgtm, size:XS

#7016 fix: longer mcp errors to show in virtual file
  gui/src/components/mainInput/Lump/sections/mcp/MCPSection.tsx
Labels: lgtm, size:M

#7021 fix: show no tools available when no tools available
  gui/src/components/mainInput/Lump/sections/tool-policies/ToolPoliciesSection.tsx
Labels: size:XS

#7034 fix: tell model no tools are available if they aren't
  gui/src/redux/thunks/streamNormalInput.ts
  gui/src/redux/util/getBaseSystemMessage.test.ts
  gui/src/redux/util/getBaseSystemMessage.ts
Labels: lgtm, size:M

#7022 fix: fix tool execute abnormal when there is no tool policy data in the local cache
  extensions/vscode/e2e/tests/GUI.test.ts
  gui/src/redux/thunks/callToolById.ts
  gui/src/redux/thunks/streamNormalInput.ts
Labels: lgtm, size:M

#7037 chore: vscode 1.1.74
  extensions/vscode/package.json
Labels: lgtm, size:XS

#7043 improve: open conversation summary be default
  gui/src/components/StepContainer/ConversationSummary.tsx
Labels: lgtm, size:XS

#7054 feat: gpt-5 support
  core/llm/llms/OpenAI.test.ts
  core/llm/llms/OpenAI.ts
  core/llm/toolSupport.ts
  gui/src/pages/AddNewModel/configs/models.ts
  gui/src/pages/AddNewModel/configs/providers.ts
  packages/llm-info/src/providers/openai.ts
  packages/openai-adapters/src/apis/OpenAI.ts
Labels: lgtm, size:M

#7042 improve: tool call spacing and margins
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/index.tsx
  gui/src/pages/gui/ToolCallDiv/index.tsx
Labels: lgtm, size:XS

#6781 Fix: Remove duplicate blocks and provide config warnings
  packages/config-yaml/src/__tests__/index.test.ts
  packages/config-yaml/src/__tests__/local-files/duplicate-test-assistant.yaml
  packages/config-yaml/src/__tests__/local-files/mcpServer.yaml
  packages/config-yaml/src/__tests__/local-files/prompt.yaml
  packages/config-yaml/src/__tests__/local-files/rules.yaml
  packages/config-yaml/src/load/blockDuplicationDetector.ts
  packages/config-yaml/src/load/unroll.ts
Labels: lgtm, size:L

#7057 chore: jetbrains 1.0.35
  extensions/intellij/gradle.properties
Labels: size:XS

#6895 fix: add autocompleteOptions in the .yaml config
  core/util/parameters.ts
  docs/customize/deep-dives/autocomplete.mdx
  docs/reference.mdx
  docs/reference/json-reference.mdx
  packages/config-types/src/index.ts
  packages/config-yaml/src/schemas/models.ts
Labels: lgtm, size:M

#6846 fix: :bug: Fix terminal use without a workspace
  core/tools/implementations/runTerminalCommand.test.ts
  core/tools/implementations/runTerminalCommand.ts
Labels: size:L

#6953 feat: Add support for LGAI EXAONE models
  core/llm/toolSupport.ts
  gui/src/pages/AddNewModel/configs/models.ts
Labels: lgtm, size:M

#7066 chore: Add action to comment on duplicate issues
  .github/workflows/similar-issues.yml
Labels: size:L

#7068 feat: add more prompt templates
  core/nextEdit/NextEditProvider.ts
  core/nextEdit/constants.ts
  core/nextEdit/context/diffFormatting.ts
  core/nextEdit/context/diffFormatting.vitest.ts
  core/nextEdit/context/processNextEditData.ts
  core/nextEdit/context/processSmallEdit.ts
  core/nextEdit/templating/NextEditPromptEngine.ts
  core/nextEdit/templating/NextEditPromptEngine.vitest.ts
  core/nextEdit/templating/model1.ts
  core/nextEdit/templating/model1.vitest.ts
  core/nextEdit/types.ts
Labels: lgtm, size:XXL

#7059 fix: remove add model system message
  core/config/util.ts
  gui/src/pages/AddNewModel/configs/models.ts
Labels: size:S

#7087 feat: Respect Org Policies
  core/config/ConfigHandler.ts
  core/config/ConfigHandler.vitest.ts
  core/config/ProfileLifecycleManager.ts
  core/config/profile/doLoadConfig.ts
  core/context/providers/_context-providers.vitest.ts
  core/control-plane/PolicySingleton.ts
  core/control-plane/client.ts
  core/core.ts
  core/protocol/core.ts
  gui/src/components/config/FatalErrorNotice.tsx
  gui/src/pages/config/UserSettingsForm.tsx
  packages/config-yaml/src/browser.ts
  packages/config-yaml/src/schemas/policy.ts
Labels: lgtm, size:L

#6777 fix: case when reranker returns invalid scores array
  core/context/providers/DocsContextProvider.ts
  core/context/retrieval/pipelines/RerankerRetrievalPipeline.ts
  core/llm/llms/Voyage.ts
Labels: lgtm, size:M

#7107 fix: prompt building
  core/llm/autodetect.ts
  core/llm/autodetect.vitest.ts
  core/llm/constants.ts
  core/nextEdit/NextEditEditableRegionCalculator.ts
  core/nextEdit/NextEditPrefetchQueue.ts
  core/nextEdit/NextEditProvider.ts
  core/nextEdit/constants.ts
  core/nextEdit/templating/NextEditPromptEngine.ts
  core/nextEdit/templating/NextEditPromptEngine.vitest.ts
  core/nextEdit/templating/instinct.ts
  core/nextEdit/templating/instinct.vitest.ts
  core/nextEdit/templating/mercuryCoderNextEdit.ts
  core/nextEdit/templating/mercuryCoderNextEdit.vitest.ts
  core/nextEdit/templating/model1.ts
  core/nextEdit/templating/utils.ts
  core/nextEdit/templating/utils.vitest.ts
  core/nextEdit/types.ts
  extensions/vscode/src/autocomplete/completionProvider.ts
  extensions/vscode/src/extension/VsCodeExtension.ts
Labels: lgtm, size:XL

#7119 chore: disable similar-issues.yml
  .github/workflows/similar-issues.yml
Labels: lgtm, size:M

#7134 docs: change readme to continuous ai
  README.md
Labels: lgtm, size:M

#7106 Create detailed review bot using 'cn'
  .github/pull_request_template.md
  .github/workflows/continue-detailed-review.yaml
  .github/workflows/continue-general-review.yaml
Labels: lgtm, size:L

#7137 chore: bump versions
  extensions/intellij/gradle.properties
  extensions/vscode/package.json
Labels: lgtm, size:XS

#7127 style: remove space between terminal command and output
  gui/src/pages/gui/ToolCallDiv/RunTerminalCommand.tsx
Labels: lgtm, size:S

#7140 chore: add `uinstinct` to auto-assign-issue.yaml
  .github/workflows/auto-assign-issue.yaml
Labels: lgtm, size:XS

#7159 fix: add Enter Enterprise License Key action
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/license/AddLicenseKey.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/license/AddLicenseKeyDialog.kt
Labels: size:L

#7156 fix: Object object in profile URI
  core/config/profile/PlatformProfileLoader.ts
Labels: size:XS

#7157 feat: add salvage functionality for security-sensitive values in Glob…
  core/util/GlobalContext.test.ts
  core/util/GlobalContext.ts
Labels: size:L

#6881 feat: implement Sentry error tracking with privacy-first anonymization
  core/.gitignore
  core/config/ConfigHandler.ts
  core/config/ProfileLifecycleManager.ts
  core/config/profile/doLoadConfig.ts
  core/control-plane/client.ts
  core/core.ts
  core/indexing/CodebaseIndexer.ts
  core/llm/index.ts
  core/package-lock.json
  core/package.json
  core/protocol/messenger/index.ts
  core/tsconfig.json
  core/util/Logger.ts
  core/util/isContinueTeamMember.ts
  core/util/logger.ts
  core/util/sentry/SentryLogger.test.ts
  core/util/sentry/SentryLogger.ts
  core/util/sentry/anonymization.test.ts
  core/util/sentry/anonymization.ts
  core/util/sentry/constants.ts
  extensions/vscode/package.json
  extensions/vscode/src/extension.ts
  extensions/vscode/src/stubs/WorkOsAuthProvider.ts
  gui/.gitignore
  gui/package-lock.json
  gui/package.json
  gui/src/components/Layout.tsx
  gui/src/hooks/CustomPostHogProvider.tsx
  gui/src/hooks/TelemetryProviders.test.tsx
  gui/src/hooks/TelemetryProviders.tsx
  gui/src/main.tsx
  gui/src/pages/config/UserSettingsForm.tsx
  gui/src/util/isContinueTeamMember.ts
  gui/vite.config.ts
Labels: lgtm, size:XXL

#7164 fix: rule colocation uri logic
  .continue/rules/bigger-picture-description-rules.md
  .continue/rules/bigger-picture-description-rules.yaml
  .continue/rules/colors.md
  .continue/rules/colors.yaml
  .continue/rules/edit-aggregator-singleton-rule.md
  .continue/rules/intellij-plugin-test-execution.md
  .continue/rules/intellij-plugin-test-execution.yaml
  .continue/rules/intellij-test-standards.md
  .continue/rules/intellij-test-standards.yaml
  .continue/rules/new-protocol-message.md
  .continue/rules/unit-testing-rules.md
  .continue/rules/unit-testing-rules.yaml
  core/config/markdown/loadCodebaseRules.ts
  core/config/markdown/loadCodebaseRules.vitest.ts
  core/config/markdown/loadMarkdownRules.ts
  core/config/profile/LocalProfileLoader.ts
  core/config/profile/doLoadConfig.ts
  core/config/yaml/loadLocalYamlBlocks.ts
  core/config/yaml/loadYaml.ts
  packages/config-yaml/src/__tests__/index.test.ts
  packages/config-yaml/src/interfaces/slugs.test.ts
  packages/config-yaml/src/interfaces/slugs.ts
  packages/config-yaml/src/load/unroll.test.ts
  packages/config-yaml/src/load/unroll.ts
  packages/config-yaml/src/markdown/createMarkdownRule.test.ts
  packages/config-yaml/src/markdown/markdownToRule.test.ts
  packages/config-yaml/src/markdown/markdownToRule.ts
  packages/config-yaml/src/registryClient.test.ts
  packages/config-yaml/src/registryClient.ts
Labels: lgtm, size:L

#7160 fix: next edit renders that should render decorations will render them properly
  .github/actions/build-vscode-extension/action.yml
  core/codeRenderer/CodeRenderer.ts
  core/nextEdit/NextEditProvider.ts
  core/nextEdit/utils.ts
  core/nextEdit/utils.vitest.ts
  extensions/vscode/src/activation/JumpManager.ts
  extensions/vscode/src/activation/JumpManager.vitest.ts
  extensions/vscode/src/activation/NextEditWindowManager.ts
Labels: lgtm, size:L

#7168 fix: vscode apply error
  extensions/vscode/src/apply/ApplyManager.ts
Labels: lgtm, size:M

#7108 chore: remove docs cache
  core/indexing/docs/DocsCache.test.ts
  core/indexing/docs/DocsCache.ts
  core/indexing/docs/DocsService.ts
Labels: lgtm, size:L

#7187 fix: unsupported themes will use dark-plus
  core/codeRenderer/CodeRenderer.ts
  core/util/text.ts
  core/util/text.vitest.ts
Labels: lgtm, size:M

#7184 feat: Add quickstart examples to docs (agent, chat, autocomplete, edit)
  docs/docs.json
  docs/getting-started/quick-start.mdx
Labels: lgtm, size:L

#7175 fix: disable tool support for moonshotai/kimi-k2:free model
  core/llm/toolSupport.test.ts
  core/llm/toolSupport.ts
Labels: lgtm, size:S

#7223 Update tutorial instructions to use /init slash command instead of unit test examples
  extensions/intellij/src/main/resources/continue_tutorial.java
  extensions/intellij/src/main/resources/continue_tutorial.py
  extensions/intellij/src/main/resources/continue_tutorial.ts
  extensions/vscode/continue_tutorial.py
Labels: size:XS

#7189 chore: fix oneper build workflow
  .github/workflows/main-build.yaml
Labels: lgtm, size:S

#7233 feat: fix the next edit provider to use the new edit endpoint
  core/nextEdit/NextEditProvider.ts
  core/nextEdit/templating/NextEditPromptEngine.ts
Labels: size:M

#7235 chore: show windows unsupported warning only once
  core/util/GlobalContext.ts
  extensions/vscode/src/activation/activate.ts
Labels: size:S

#7239 fix: model specification for next edit
  docs/features/autocomplete/next-edit.mdx
Labels: size:S

#7232 feat: update openai-adapter to support Inception models
  core/llm/autodetect.ts
  core/llm/constants.ts
  core/llm/llms/Inception.ts
  core/nextEdit/NextEditProvider.ts
  core/nextEdit/constants.ts
  core/nextEdit/templating/NextEditPromptEngine.ts
  packages/openai-adapters/src/apis/Inception.ts
Labels: size:L

#7222 feat: check for model before using full file diffs
  core/nextEdit/templating/NextEditPromptEngine.ts
  core/nextEdit/templating/NextEditPromptEngine.vitest.ts
  extensions/vscode/src/activation/SelectionChangeManager.ts
  extensions/vscode/src/autocomplete/completionProvider.ts
  extensions/vscode/src/extension/VsCodeExtension.ts
Labels: lgtm, size:M

#7218 feat: select assistant polishes
  core/config/createNewAssistantFile.ts
  core/core.ts
  core/protocol/core.ts
  core/protocol/passThrough.ts
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt
  gui/src/components/AssistantAndOrgListbox/index.tsx
Labels: size:L

#7244 fix: openai adapters
  packages/openai-adapters/package-lock.json
  packages/openai-adapters/package.json
Labels: lgtm, size:XS

#7238 fix: sanitize proxy settings + add NO_PROXY support + add unit tests
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/process/ContinueBinaryProcess.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/proxy/ProxySettings.kt
  extensions/intellij/src/test/kotlin/com/github/continuedev/continueintellijextension/unit/ProxySettingsTest.kt
Labels: lgtm, size:M

#7263 chore: bump package.json
  extensions/vscode/package.json
Labels: size:XS

#7224 feat: update default-included context providers
  binary/package.json
  core/config/default.ts
  core/config/load.ts
  core/config/loadContextProviders.ts
  core/config/loadContextProviders.vitest.ts
  core/config/profile/doLoadConfig.ts
  core/config/yaml/loadYaml.ts
  core/context/providers/CodebaseContextProvider.ts
  core/core.ts
  core/index.d.ts
  core/indexing/CodebaseIndexer.test.ts
  core/indexing/CodebaseIndexer.ts
  core/util/paths.ts
Labels: lgtm, size:XL

#7269 feat: wrap each recently viewed code snippet inside a token block
  core/nextEdit/templating/NextEditPromptEngine.vitest.ts
  core/nextEdit/templating/mercuryCoderNextEdit.ts
  core/nextEdit/templating/mercuryCoderNextEdit.vitest.ts
Labels: lgtm, size:S

#7240 fix: remove jarowinkler similarity for search and replace
  core/edit/searchAndReplace/findSearchMatch.strategy.test.ts
  core/edit/searchAndReplace/findSearchMatch.test.ts
  core/edit/searchAndReplace/findSearchMatch.ts
Labels: lgtm, size:L

#7272 fix: max abort listeners warning
  extensions/cli/src/streamChatResponse.ts
  extensions/cli/src/ui/hooks/useChat.ts
  extensions/cli/src/util/exponentialBackoff.ts
  extensions/cli/src/util/withExponentialBackoff.test.ts
Labels: size:L

#7273 fix: beta-release with correct path
  .github/workflows/beta-release.yml
Labels: size:XS

#7104 feat: :sparkles: Add gpt-oss to the bedrock provider
  core/llm/toolSupport.ts
Labels: lgtm, size:XS

#7293 Prevent zero click image rendering
  gui/src/components/StyledMarkdownPreview/SecureImageComponent.test.tsx
  gui/src/components/StyledMarkdownPreview/SecureImageComponent.tsx
  gui/src/components/StyledMarkdownPreview/index.tsx
Labels: size:L

#7280 fix: :bug: Fix lsTool Exclusions
  core/tools/implementations/lsTool.ts
Labels: lgtm, size:XS

#7257 chore: enable native tool support for kimi k2
  core/llm/toolSupport.ts
Labels: lgtm, size:XS

#7296 Nate/more-warnings-fixes
  .github/actions/run-jetbrains-tests/action.yml
  .github/workflows/cli-pr-checks.yml
  core/package-lock.json
  core/package.json
  extensions/cli/BUILD.md
  extensions/cli/build.mjs
  extensions/cli/package-lock.json
  extensions/cli/package.json
  extensions/cli/smoke-test.mjs
  extensions/cli/src/configLoader.ts
  extensions/cli/src/sentry-profiling.ts
  extensions/cli/src/sentry.ts
  extensions/cli/src/services/FileIndexService.ts
  extensions/cli/src/services/ModelService.ts
  extensions/cli/src/slashCommands.test.ts
  extensions/cli/src/slashCommands.ts
  extensions/cli/src/ui/UserInput.tsx
  extensions/cli/stubs/react-devtools-core.js
  extensions/cli/validate-aliases.mjs
Labels: size:XL

#7311 fix: HOTFIX unknown context provider file
  core/config/loadContextProviders.ts
  core/context/providers/index.ts
Labels: lgtm, size:S

#7340 fix: move dependencies to devDependencies and add @sentry/profiling-node
  core/llm/llm.test.ts
  extensions/cli/package-lock.json
  extensions/cli/package.json
Labels: lgtm, size:S

#7215 docs: Update Ollama guide documentation
  .github/workflows/docs.yml
  docs/customize/model-providers/top-level/ollama.mdx
  docs/guides/ollama-guide.mdx
Labels: lgtm, size:L

#7172 feat: add tool support for Novita provider models
  core/llm/toolSupport.test.ts
  core/llm/toolSupport.ts
Labels: lgtm, size:M

#7339 fix: update broken links to Next Edit documentation
  docs/docs.json
  docs/features/autocomplete/model-setup.mdx
  docs/features/edit/how-it-works.mdx
Labels: size:XS

#7286 Respect "useReranking" field from configuration
  core/context/retrieval/retrieval.ts
Labels: lgtm, size:XS

#7345 docs: update recommended model links
  docs/customization/models.mdx
  docs/customize/model-providers/top-level/azure.mdx
  docs/customize/model-providers/top-level/deepseek.mdx
  docs/customize/model-providers/top-level/gemini.mdx
  docs/customize/model-providers/top-level/ollama.mdx
  docs/features/agent/model-setup.mdx
  docs/features/autocomplete/model-setup.mdx
  docs/features/chat/model-setup.mdx
  docs/features/edit/model-setup.mdx
Labels: lgtm, size:M

#7247 feat: add brief apply formatting instructions to agent/plan, current file description update
  core/llm/defaultSystemMessages.ts
  core/tools/definitions/readCurrentlyOpenFile.ts
Labels: lgtm, size:S

#7312 refactor: code cleanup for next edit
  core/llm/autodetect.ts
  core/llm/autodetect.vitest.ts
  core/llm/constants.ts
  core/nextEdit/NextEditProvider.ts
  core/nextEdit/NextEditProviderFactory.ts
  core/nextEdit/constants.ts
  core/nextEdit/providers/BaseNextEditProvider.ts
  core/nextEdit/providers/InstinctNextEditProvider.ts
  core/nextEdit/providers/MercuryCoderNextEditProvider.ts
  core/nextEdit/templating/NextEditPromptEngine.ts
  core/nextEdit/templating/NextEditPromptEngine.vitest.ts
  core/nextEdit/types.ts
  core/nextEdit/utils.ts
  core/nextEdit/utils.vitest.ts
Labels: lgtm, size:XXL

#7347 chore: upgrade to 1.3.0
  extensions/vscode/package.json
Labels: lgtm, size:XS

#7346 fix: stop dependencies from logging to stdout when in tui mode
  extensions/cli/src/commands/chat.ts
  extensions/cli/src/index.ts
  extensions/cli/src/init.ts
  extensions/cli/src/util/consoleOverride.ts
  extensions/cli/vitest.setup.ts
Labels: size:L

#7352 fix: name check
  .github/workflows/preview.yaml
Labels: size:XS

#7243 fix: redirect agents -> assistants
  docs/docs.json
Labels: lgtm, size:XS

#7356 Update package.json
  extensions/vscode/package.json
Labels: size:XS

#7379 feat: --mcp + --model flagss and some refactoring
  .github/workflows/cli-pr-checks.yml
  extensions/cli/src/args-mcp.test.ts
  extensions/cli/src/args.ts
  extensions/cli/src/auth/workos-org.test.ts
  extensions/cli/src/auth/workos.helpers.ts
  extensions/cli/src/commands/BaseCommandOptions.ts
  extensions/cli/src/commands/chat.ts
  extensions/cli/src/commands/serve.test.ts
  extensions/cli/src/commands/serve.ts
  extensions/cli/src/configEnhancer.test.ts
  extensions/cli/src/configEnhancer.ts
  extensions/cli/src/configLoader.ts
  extensions/cli/src/e2e/headless-anthropic-api-key.test.ts
  extensions/cli/src/e2e/headless-org-flag.test.ts
  extensions/cli/src/flags/flagValidator.ts
  extensions/cli/src/hubLoader.test.ts
  extensions/cli/src/hubLoader.ts
  extensions/cli/src/index.ts
  extensions/cli/src/integration/rule-duplication.test.ts
  extensions/cli/src/loadMcpFromHub.test.ts
  extensions/cli/src/mcp-flag.integration.test.ts
  extensions/cli/src/onboarding.ts
  extensions/cli/src/services/BaseService.ts
  extensions/cli/src/services/ConfigService.test.ts
  extensions/cli/src/services/ConfigService.ts
  extensions/cli/src/services/ModelService.direct.test.ts
  extensions/cli/src/services/ModelService.refactored.ts
  extensions/cli/src/services/ModelService.test.ts
  extensions/cli/src/services/ModelService.ts
  extensions/cli/src/services/index.ts
  extensions/cli/src/services/types.ts
  extensions/cli/src/shared-options.ts
  extensions/cli/src/ui/IntroMessage.test.tsx
  extensions/cli/src/ui/IntroMessage.tsx
  extensions/cli/src/ui/index.ts
  extensions/cli/test-fixtures/model-switch-test-config.yaml
  package-lock.json
Labels: size:XXL

#7323 fix: grep escaped chars and empty results
  core/tools/implementations/fetchUrlContent.ts
  core/tools/implementations/fetchUrlContent.vitest.ts
  core/tools/implementations/globSearch.ts
  core/tools/implementations/grepSearch.ts
  core/tools/implementations/lsTool.ts
  core/tools/implementations/searchWeb.ts
  core/tools/implementations/searchWeb.vitest.ts
  core/tools/implementations/viewDiff.ts
  core/tools/implementations/viewDiff.vitest.ts
  core/tools/parseArgs.ts
  core/tools/parseArgs.vitest.ts
  core/util/regexValidator.ts
  core/util/regexValidator.vitest.ts
Labels: size:XL

#7210 Fix reranking on vllm provider
  core/llm/llms/Vllm.ts
Labels: lgtm, size:XS

#7367 feat: diff UI for find and replace tools
  gui/package-lock.json
  gui/package.json
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/ApplyActions.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/FileInfo.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/index.tsx
  gui/src/pages/gui/ToolCallDiv/FindAndReplace.test.tsx
  gui/src/pages/gui/ToolCallDiv/FindAndReplace.tsx
  gui/src/pages/gui/ToolCallDiv/FunctionSpecificToolCallDiv.tsx
  gui/src/redux/slices/sessionSlice.ts
  gui/src/redux/thunks/enhanceParsedArgs.ts
  gui/src/redux/thunks/streamNormalInput.ts
  gui/src/util/clientTools/multiEditImpl.ts
  gui/src/util/clientTools/searchReplaceImpl.ts
  gui/src/util/clientTools/singleFindAndReplaceImpl.ts
Labels: lgtm, size:XL

#7394 Add continue-on-error to JetBrains plugin publish steps
  .github/workflows/jetbrains-release.yaml
Labels: size:XS

#7397 fix: remove non recommended models
  docs/customization/models.mdx
Labels: lgtm, size:S

#7375 fix: CSS files not being indexed (#7072)
  core/indexing/chunk/chunk.ts
Labels: lgtm, size:S

#7400 feat: allow/blocklisted blocks in unrollAssistant
  packages/config-yaml/src/__tests__/index.test.ts
  packages/config-yaml/src/load/unroll.ts
Labels: lgtm, size:L

#7329 fix: add Run Extension (standalone) config
  extensions/intellij/.run/Run Continue (CE).run.xml
  extensions/intellij/.run/Run Continue.run.xml
  extensions/intellij/.run/Run Extension (standalone).run.xml
  extensions/intellij/.run/Run Extension (use TCP).run.xml
  extensions/intellij/.run/Run Extension.run.xml
Labels: lgtm, size:M

#7389 fix: render Ollama thinking messages
  core/llm/llms/Ollama.ts
Labels: lgtm, size:XS

#7333 docs: better openrouter info
  docs/customize/model-providers/more/openrouter.mdx
Labels: lgtm, size:M

#7131 Jacob/con 3353
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/ContinueInlineCompletionProvider.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/DiffStreamService.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/listeners/ActiveHandlerManager.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/listeners/DocumentChangeTracker.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/listeners/SelectionChangeManager.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/listeners/TypingSessionHandler.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/nextEdit/NextEditJumpHandler.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/nextEdit/NextEditJumpManager.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/nextEdit/NextEditService.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/nextEdit/NextEditUtils.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/nextEdit/NextEditWindowHandler.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/nextEdit/NextEditWindowManager.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/nextEdit/types.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/ContinuePluginService.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/utils/InlineCompletionUtils.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/utils/Utils.kt
  extensions/intellij/src/main/resources/META-INF/plugin.xml
  extensions/intellij/src/test/kotlin/com/github/continuedev/continueintellijextension/unit/CheckFimTest.kt
Labels: lgtm, size:XXL

#7315 feat: continue tool calls after rejection
  core/config/sharedConfig.ts
  core/index.d.ts
  gui/src/pages/config/UserSettingsForm.tsx
  gui/src/redux/thunks/cancelToolCall.ts
  gui/src/redux/thunks/streamResponseAfterToolCall.ts
Labels: lgtm, size:M

#7007 feat: improvements to docs indexing status visibility
  core/core.ts
  core/indexing/docs/DocsService.ts
  core/protocol/core.ts
  core/protocol/passThrough.ts
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt
  gui/src/components/mainInput/Lump/sections/docs/DocsDetailsDialog.tsx
  gui/src/components/mainInput/Lump/sections/docs/DocsIndexingStatus.test.tsx
  gui/src/components/mainInput/Lump/sections/docs/DocsIndexingStatus.tsx
  gui/src/components/mainInput/Lump/sections/docs/IndexedPagesTooltip.test.tsx
  gui/src/components/mainInput/Lump/sections/docs/IndexedPagesTooltip.tsx
  gui/src/redux/thunks/streamResponse.test.ts
  gui/src/redux/thunks/streamResponse_errorHandling.test.ts
  gui/src/redux/thunks/streamResponse_toolCalls.test.ts
  gui/src/util/test/mockStore.ts
Labels: size:XL

#7438 fix: JetBrains QoL improvement and bugfixes
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/ContinueInlineCompletionProvider.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/nextEdit/NextEditJumpManager.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/nextEdit/NextEditUtils.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/nextEdit/NextEditWindowManager.kt
Labels: lgtm, size:L

#7403 fix: :lipstick: Align component styles
  gui/src/components/UnifiedTerminal/UnifiedTerminal.tsx
  gui/src/pages/gui/ToolCallDiv/FindAndReplace.tsx
  gui/src/styles/theme.ts
  gui/tailwind.config.cjs
Labels: lgtm, size:M

#7369 Batch tokens generated events
  core/context/providers/index.ts
  core/indexing/CodebaseIndexer.ts
  core/llm/index.ts
  core/util/TokensBatchingService.ts
  core/util/posthog.ts
Labels: size:L

#7444 chore: bump package.json
  extensions/vscode/package.json
Labels: size:XS

#7446 fix: split thinking and chat messages when Ollama is not streaming
  core/llm/llms/Ollama.ts
Labels: size:M

#7466 feat: use on prem proxy in CLI
  extensions/cli/src/configLoader.ts
  extensions/cli/src/services/ModelService.ts
  extensions/cli/src/ui/ToolResultSummary.tsx
Labels: lgtm, size:S

#7136 feat: Add Tetrate Agent Router Service as a provider
  core/llm/llms/TARS.ts
  core/llm/llms/index.ts
  docs/customize/model-providers/more/tetrate_agent_router_service.mdx
  extensions/vscode/config_schema.json
  gui/public/logos/TetrateAgentRouterService.png
  gui/src/pages/AddNewModel/configs/providers.ts
Labels: lgtm, size:M

#7487 chore: remove unused search and replace tool
  core/edit/searchAndReplace/findSearchMatch.strategy.test.ts
  core/edit/searchAndReplace/findSearchMatch.test.ts
  core/edit/searchAndReplace/findSearchMatch.ts
  core/edit/searchAndReplace/parseSearchReplaceBlock.test.ts
  core/edit/searchAndReplace/parseSearchReplaceBlock.ts
  core/tools/builtIn.ts
  core/tools/definitions/editFile.ts
  core/tools/definitions/index.ts
  core/tools/definitions/multiEdit.ts
  core/tools/definitions/searchAndReplaceInFile.ts
  core/tools/definitions/singleFindAndReplace.ts
  core/tools/index.ts
  gui/src/pages/gui/ToolCallDiv/FunctionSpecificToolCallDiv.tsx
  gui/src/pages/gui/ToolCallDiv/index.tsx
  gui/src/redux/slices/sessionSlice.ts
  gui/src/redux/thunks/enhanceParsedArgs.ts
  gui/src/util/clientTools/callClientTool.ts
  gui/src/util/clientTools/searchReplaceImpl.test.ts
  gui/src/util/clientTools/searchReplaceImpl.ts
  gui/src/util/migrateLocalStorage.ts
Labels: size:XXL

#7470 Reduce test flake
  .github/actions/check-llm-changes/action.yml
  .github/workflows/pr-checks.yaml
  core/indexing/docs/crawlers/DocsCrawler.test.ts
Labels: lgtm, size:L

#7469 refactor: next edit model provider rename
  core/nextEdit/NextEditPrefetchQueue.ts
  core/nextEdit/NextEditProvider.ts
  core/nextEdit/NextEditProviderFactory.ts
  core/nextEdit/providers/BaseNextEditProvider.ts
  core/nextEdit/providers/InstinctNextEditProvider.ts
  core/nextEdit/providers/MercuryCoderNextEditProvider.ts
Labels: lgtm, size:S

#7463 fix: recover Continue process after unexpected exceptions
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessenger.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessengerManager.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/process/BackoffCalculator.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/process/ContinueBinaryProcess.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/process/ContinueProcessHandler.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/proxy/ProxyPoolingActivity.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/ContinuePluginService.kt
  extensions/intellij/src/test/kotlin/com/github/continuedev/continueintellijextension/unit/BackoffCalculatorTest.kt
Labels: lgtm, size:L

#7499 cai: mention continue workflow
  .github/workflows/respond-to-cubic.yaml
Labels: size:L
