Repository continuedev/continue, pull requests merged in 2025-07, with the labels that each got.

#6336 fix: Fix retrieval reranker sorting issue
  core/context/retrieval/pipelines/RerankerRetrievalPipeline.ts
Labels: lgtm, size:XS

#6372 feat: Attach thread dumps to Sentry events + report caught exceptions
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/error/ContinueErrorService.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/error/ContinueErrorSubmitter.kt
Labels: lgtm, size:L

#6388 Jacob/feature/dynamic switch autocomplete nextedit
  core/nextEdit/diff/diff.ts
  extensions/vscode/src/activation/NextEditWindowManager.ts
  extensions/vscode/src/autocomplete/completionProvider.ts
Labels: size:L

#6373 build: Simplify runIde args
  extensions/intellij/build.gradle.kts
Labels: lgtm, size:XS

#6392 Quick fix: removing functionally redundant items in dev data toolusage
  core/tools/callTool.ts
  gui/package-lock.json
  gui/src/redux/util/index.ts
  packages/config-yaml/src/schemas/data/toolUsage/index.ts
  packages/config-yaml/src/schemas/data/toolUsage/v0.2.0.ts
Labels: lgtm, size:XS

#6404 refactor: Remove unused bundle resource
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/MyBundle.kt
  extensions/intellij/src/main/resources/META-INF/plugin.xml
  extensions/intellij/src/main/resources/messages/MyBundle.properties
Labels: lgtm, size:M

#6233 feat: continue init prompt
  core/promptFiles/getPromptFiles.ts
Labels: lgtm, size:M

#6396 Simplify tool names
  core/tools/builtIn.ts
  docs/docs/agent/how-it-works.md
  docs/docs/customize/deep-dives/rules.mdx
  extensions/vscode/e2e/test-continue-yaml/config.yaml
  extensions/vscode/e2e/test-continue/config.json
  extensions/vscode/e2e/tests/GUI.test.ts
  gui/src/hooks/ParallelListeners.tsx
  gui/src/pages/gui/ToolCallDiv/index.tsx
  gui/src/redux/slices/uiSlice.ts
  gui/src/util/migrateLocalStorage.ts
Labels: lgtm, size:L

#6304 chore: build packages in jetbrains release
  .github/workflows/jetbrains-release.yaml
Labels: lgtm, size:S

#6355 chore: conditional tooltip on reasoning btn
  gui/src/components/mainInput/InputToolbar.tsx
Labels: lgtm, size:XS

#6380 chore: update toolSupport.ts
  core/llm/toolSupport.ts
Labels: lgtm, size:XS

#6364 fix: prevent lines removal on docstring insertion
  extensions/vscode/src/commands.ts
Labels: lgtm, size:XS

#6408 Update CLA allowlist to include additional contributors
  .github/workflows/cla.yaml
Labels: lgtm, size:XS

#6414 Add support for isWorkspaceRemote message type in IntelliJ extension
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
Labels: lgtm, size:S

#6393 Revert "Quick fix: removing functionally redundant items in dev data toolusage"
  core/tools/callTool.ts
  gui/package-lock.json
  gui/src/redux/util/index.ts
  packages/config-yaml/src/schemas/data/toolUsage/index.ts
  packages/config-yaml/src/schemas/data/toolUsage/v0.2.0.ts
Labels: lgtm, size:XS

#6416 fix: pasting images
  gui/src/components/mainInput/TipTapEditor/utils/editorConfig.ts
Labels: lgtm, size:S

#6419 feat: add `claude-opus-4` tool support for bedrock models
  core/llm/toolSupport.ts
Labels: lgtm, size:S

#6381 Mode cycling focus fix
  gui/src/components/ModeSelect/ModeSelect.tsx
Labels: lgtm, size:XS

#6415 Remove unused onlyOneInsertion param
  core/core.ts
  core/edit/streamDiffLines.ts
  extensions/vscode/src/commands.ts
  extensions/vscode/src/diff/vertical/manager.ts
Labels: lgtm, size:S

#6423 fix: :bug: The edit rules button doesn't open the rule file
  core/config/markdown/loadCodebaseRules.ts
  core/config/markdown/loadMarkdownRules.ts
Labels: lgtm, size:XS

#6154 add llamastack support
  core/llm/llms/LlamaStack.ts
  core/llm/llms/index.ts
  docs/docs/customize/model-providers/more/llamastack.mdx
  packages/openai-adapters/src/apis/LlamaStack.ts
  packages/openai-adapters/src/index.ts
  packages/openai-adapters/src/types.ts
Labels: lgtm, size:L

#6424 Bump IntelliJ plugin version to 1.0.27
  extensions/intellij/gradle.properties
Labels: size:XS

#6376 fix: support local slugs in document link provider
  extensions/vscode/src/extension/ConfigYamlDocumentLinkProvider.ts
Labels: lgtm, size:M

#6427 feat: add a sessions loading indicator
  gui/src/components/History/index.tsx
  gui/src/hooks/ParallelListeners.tsx
  gui/src/redux/slices/sessionSlice.ts
  gui/src/redux/thunks/session.ts
Labels: lgtm, size:M

#6390 Prevent entire indexing process from stopping on error and surface messages to Indexing menu
  core/index.d.ts
  core/indexing/CodeSnippetsIndex.ts
  core/indexing/CodebaseIndexer.ts
  core/indexing/FullTextSearchCodebaseIndex.ts
  core/indexing/README.md
  gui/src/pages/config/IndexingProgress/IndexingProgress.tsx
  gui/src/pages/config/IndexingProgress/IndexingProgressErrorText.tsx
Labels: lgtm, size:L

#6426 Fix install-all-dependencies script
  scripts/install-dependencies.ps1
  scripts/install-dependencies.sh
Labels: size:S

#6418 fix duplicate tools bug
  binary/package-lock.json
  core/config/load.ts
  core/tools/index.ts
  extensions/vscode/package-lock.json
  gui/package-lock.json
Labels: lgtm, size:S

#6441 Less flashy truncate to tool call icon
  gui/src/pages/gui/ToolCallDiv/ToolTruncateHistoryIcon.tsx
Labels: lgtm, size:S

#6440 Disallow read file tools to add files that exceed half of context length
  core/tools/implementations/readCurrentlyOpenFile.ts
  core/tools/implementations/readFile.ts
  core/tools/implementations/readFileLimit.ts
Labels: lgtm, size:M

#6434 @codebase use tool calling (under experimental flag)
  core/config/sharedConfig.ts
  core/context/retrieval/pipelines/BaseRetrievalPipeline.ts
  core/context/retrieval/pipelines/NoRerankerRetrievalPipeline.ts
  core/context/retrieval/pipelines/RerankerRetrievalPipeline.ts
  core/context/retrieval/retrieval.ts
  core/core.ts
  core/index.d.ts
  core/tools/callTool.ts
  core/tools/definitions/globSearch.ts
  core/tools/implementations/grepSearch.ts
  gui/src/pages/config/UserSettingsForm.tsx
Labels: lgtm, size:L

#6420 feat: custom llmstxt plugin
  docs/docusaurus.config.js
  docs/plugins/custom-llms-txt.js
Labels: lgtm, size:L

#6194 fix(autocomplete): trim trailing <|file_separator|> for Gemini/Gemma
  core/autocomplete/postprocessing/index.ts
Labels: lgtm, size:XS

#6318 UI Polish
  .continue/rules/css-units.md
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/GetTheme.kt
  gui/src/components/Layout.tsx
  gui/src/components/StyledMarkdownPreview/index.tsx
  gui/src/components/index.ts
  gui/src/components/mainInput/ContinueInputBox.tsx
  gui/src/components/mainInput/GradientBorder.tsx
  gui/src/components/mainInput/InputToolbar/EnterButton.tsx
  gui/src/components/mainInput/Lump/index.tsx
  gui/src/components/mainInput/TipTapEditor/TipTapEditor.tsx
  gui/src/components/mainInput/TipTapEditor/components/StyledComponents.ts
  gui/src/styles/theme.ts
  gui/tailwind.config.cjs
Labels: lgtm, size:L

#6442 Add edit history sequences to nextEdit dev data for easier processing
  core/core.ts
  core/nextEdit/context/prevEditLruCache.ts
  core/nextEdit/context/processNextEditData.ts
  packages/config-yaml/src/schemas/data/index.ts
  packages/config-yaml/src/schemas/data/nextEditWithHistory/index.ts
  packages/config-yaml/src/schemas/data/nextEditWithHistory/v0.2.0.ts
Labels: lgtm, size:L

#6412 Fix: resolve the context retrieval issue for codebase and docs
  core/core.ts
Labels: lgtm, size:S

#6428 Add o-series model autodetection and comprehensive test coverage
  core/llm/autodetect.ts
  core/llm/autodetect.vitest.ts
  core/llm/index.ts
Labels: size:L

#6410 Improve history search with multi-stage matching algorithm
  gui/src/components/History/index.tsx
Labels: size:M

#6443 Jacob/feature/nextedit telemetry
  core/nextEdit/NextEditLoggingService.ts
  core/nextEdit/NextEditProvider.ts
  core/nextEdit/templating/NextEditPromptEngine.ts
  core/nextEdit/types.ts
  extensions/vscode/src/activation/NextEditWindowManager.ts
  extensions/vscode/src/autocomplete/completionProvider.ts
  extensions/vscode/src/commands.ts
  packages/config-yaml/src/schemas/data/index.ts
  packages/config-yaml/src/schemas/data/nextEditOutcome/index.ts
  packages/config-yaml/src/schemas/data/nextEditOutcome/v0.2.0.ts
Labels: size:XL

#6444 Bump version to 1.1.56
  extensions/vscode/package.json
Labels: size:XS

#6458 Update CLA document in workflow
  docs/docs/CLA.md
Labels: lgtm, size:XS

#6462 Nate/hotfix-read-file-tool
  core/llm/countTokens.ts
  extensions/vscode/package.json
Labels: lgtm, size:XS

#6456 Nate/indexing-and-retrieval-fixes
  core/context/retrieval/pipelines/RerankerRetrievalPipeline.ts
  core/indexing/LanceDbIndex.ts
Labels: lgtm, size:XS

#6453 fix continue yaml config due to multiple config declarations
  extensions/vscode/src/activation/activate.ts
Labels: lgtm, size:S

#6303 improve: instruct model when no context results were retrieved
  core/context/providers/_context-providers.vitest.ts
  core/context/retrieval/retrieval.ts
  core/core.ts
  core/index.d.ts
  core/protocol/core.ts
  core/tools/implementations/codebaseTool.ts
  extensions/vscode/src/quickEdit/ContextProvidersQuickPick.ts
  gui/src/components/mainInput/AtMentionDropdown/index.tsx
  gui/src/components/mainInput/TipTapEditor/utils/renderPromptv1.ts
  gui/src/components/mainInput/TipTapEditor/utils/resolveEditorContent.ts
  gui/src/redux/thunks/edit.ts
  gui/src/redux/thunks/streamResponse.ts
Labels: lgtm, size:M

#6465 rolling back edit logging temporarily — issues with repo detection
  core/nextEdit/context/processNextEditData.ts
Labels: lgtm, size:M

#6467 don't expand edit tool codeblocks by default
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/CollapsibleContainer.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/index.tsx
  gui/src/components/StyledMarkdownPreview/index.tsx
  gui/src/pages/gui/ToolCallDiv/EditFile.tsx
Labels: size:M

#6474 Quick fixes (codebase related)
  core/context/retrieval/pipelines/BaseRetrievalPipeline.ts
  core/indexing/LanceDbIndex.ts
  gui/src/redux/slices/sessionSlice.ts
Labels: size:S

#6484 fix: Attach environment type to reported exceptions
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/error/ContinueErrorService.kt
Labels: lgtm, size:XS

#6280 feat: adds cwd to the MCP yaml as an option.
  core/config/types.ts
  core/config/yaml/loadYaml.ts
  core/config/yaml/loadYaml.vitest.ts
  core/context/mcp/MCPConnection.ts
  core/context/mcp/MCPConnection.vitest.ts
  core/index.d.ts
  docs/docs/customize/deep-dives/mcp.mdx
  docs/docs/customize/yaml-migration.mdx
  docs/docs/reference.mdx
  packages/config-yaml/src/schemas/index.ts
Labels: size:L

#6439 Truncate large agent tool output
  core/tools/implementations/fetchUrlContent.ts
  core/tools/implementations/fetchUrlContent.vitest.ts
  core/tools/implementations/lsTool.ts
  core/tools/implementations/lsTool.vitest.ts
  core/tools/implementations/searchWeb.ts
  core/tools/implementations/searchWeb.vitest.ts
  core/tools/implementations/viewDiff.ts
  core/tools/implementations/viewDiff.vitest.ts
Labels: lgtm, size:XL

#6499 feat: Bedrock OpenAI adapter
  core/config/load.ts
  core/config/yaml/models.ts
  core/index.d.ts
  core/llm/constants.ts
  core/llm/index.ts
  core/llm/llms/Bedrock.ts
  core/llm/llms/stubs/ContinueProxy.ts
  extensions/vscode/config_schema.json
  gui/src/pages/config/ModelRoleSelector.tsx
  packages/config-yaml/src/load/clientRender.ts
  packages/config-yaml/src/schemas/models.ts
  packages/continue-sdk/typescript/src/createOpenAIClient.ts
  packages/openai-adapters/package-lock.json
  packages/openai-adapters/package.json
  packages/openai-adapters/src/apis/Bedrock.ts
  packages/openai-adapters/src/index.ts
  packages/openai-adapters/src/types.ts
Labels: size:XL

#6505 chore: config-yaml v96
  packages/config-yaml/package.json
Labels: lgtm, size:XS

#6517 chore: bump
  extensions/vscode/package.json
Labels: lgtm, size:XS

#6108 fix: enable parsing of OpenAI-compatible agent mode messages
  gui/src/redux/slices/sessionSlice.test.ts
  gui/src/redux/slices/sessionSlice.ts
Labels: lgtm, size:XL

#6475 Polishing find / replace tool (UI, prompt)
  core/llm/toolSupport.ts
  core/tools/definitions/searchAndReplaceInFile.ts
  core/tools/index.ts
  extensions/vscode/e2e/tests/GUI.test.ts
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  extensions/vscode/src/diff/vertical/handler.ts
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/index.tsx
  gui/src/pages/gui/ToolCallDiv/EditFile.tsx
  gui/src/pages/gui/ToolCallDiv/FunctionSpecificToolCallDiv.tsx
  gui/src/pages/gui/ToolCallDiv/index.tsx
  gui/src/redux/thunks/streamNormalInput.ts
Labels: lgtm, size:L

#6515 fix: use correct styling on truncate btn
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/ToolbarButtonWithTooltip.tsx
  gui/src/pages/gui/ToolCallDiv/ToolCallArgs.tsx
  gui/src/pages/gui/ToolCallDiv/ToolTruncateHistoryIcon.tsx
Labels: size:M

#6511 feat: add 'uri' for context items for http context provider
  core/context/providers/HttpContextProvider.ts
  docs/docs/customize/custom-providers.mdx
Labels: lgtm, size:M

#6522 Expand editOutcome schema with code fields + add rules to chatInteraction
  .continue/rules/dev-data-guide.md
  core/llm/rules/getSystemMessageWithRules.ts
  gui/src/redux/thunks/streamNormalInput.ts
  packages/config-yaml/src/schemas/data/chatInteraction/index.ts
  packages/config-yaml/src/schemas/data/chatInteraction/v0.2.0.ts
  packages/config-yaml/src/schemas/data/editOutcome/v0.2.0.ts
Labels: lgtm, size:L

#6523 Fix: improved Documentation Indexing and Submenu Updates
  core/context/providers/DocsContextProvider.ts
  core/indexing/docs/DocsService.ts
Labels: lgtm, size:L

#6520 style: update sambanova logo
  gui/public/logos/sambanova.png
Labels: lgtm, size:XS

#6526 feat: VertexAI keyFile, keyJson, and express/apiKey support
  core/llm/llms/VertexAI.ts
  docs/docs/customize/model-providers/top-level/vertexai.mdx
Labels: lgtm, size:L

#6540 fix: Nvidia Agent and handle different arg streaming styles
  core/llm/autodetect.ts
  gui/src/util/toolCallState.test.ts
  gui/src/util/toolCallState.ts
Labels: size:L

#6536 docs: return autocomplete setup
  docs/docs/customize/deep-dives/mcp.mdx
  docs/docs/features/agent/context-selection.mdx
  docs/docs/features/agent/how-to-customize.mdx
  docs/docs/features/agent/model-setup.mdx
  docs/docs/features/autocomplete/context-selection.mdx
  docs/docs/features/autocomplete/how-to-customize.mdx
  docs/docs/features/autocomplete/model-setup.mdx
  docs/docs/features/chat/context-selection.mdx
  docs/docs/features/chat/how-to-customize.mdx
  docs/docs/features/chat/model-setup.mdx
  docs/docs/features/edit/context-selection.mdx
  docs/docs/features/edit/how-to-customize.mdx
  docs/docs/features/edit/model-setup.mdx
  docs/docusaurus.config.js
Labels: lgtm, size:L

#6533 chore: remove feedback dialog
  gui/src/components/dialogs/FeedbackDialog.tsx
  gui/src/pages/gui/Chat.tsx
  gui/src/redux/slices/uiSlice.ts
  gui/src/util/localStorage.ts
Labels: lgtm, size:M

#6547 chore: vs code 1.1.60
  extensions/vscode/package.json
Labels: lgtm, size:XS

#6394 feat: prefix folder path for colocated rules
  packages/config-yaml/src/markdown/createMarkdownRule.test.ts
  packages/config-yaml/src/markdown/markdownToRule.test.ts
  packages/config-yaml/src/markdown/markdownToRule.ts
Labels: lgtm, size:L

#6549 bug fix for code snippets index in IntelliJ Plugin
  binary/.gitignore
  binary/build.js
  binary/pkgJson/darwin-arm64/package.json
  binary/pkgJson/darwin-x64/package.json
  binary/pkgJson/linux-arm64/package.json
  binary/pkgJson/linux-x64/package.json
  binary/pkgJson/win32-arm64/package.json
  binary/pkgJson/win32-x64/package.json
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt
Labels: lgtm, size:M

#6537 Add config schema review rule documentation
  packages/config-yaml/src/schemas/review.rule.md
Labels: lgtm, size:XS

#6564 fix: :mute: The safeParseToolCallArgs function is logging excessively
  core/tools/parseArgs.ts
Labels: lgtm, size:XS

#6561 fix: only set inactive when conversation isn't continuing
  gui/src/redux/thunks/callCurrentTool.ts
  gui/src/redux/thunks/streamNormalInput.ts
Labels: lgtm, size:XS

#6446 run shell path async to avoid blocking config load
  core/context/mcp/MCPConnection.ts
  core/context/mcp/MCPConnection.vitest.ts
  core/util/shellPath.ts
Labels: lgtm, size:M

#6555 chore: create test-running-guide.md
  .continue/rules/test-running-guide.md
Labels: lgtm, size:S

#6554 feat: lock indexing until completion
  core/core.ts
  core/index.d.ts
  core/indexing/CodebaseIndexer.ts
  core/indexing/refreshIndex.ts
  gui/src/pages/config/IndexingProgress/IndexingProgress.tsx
  gui/src/pages/config/IndexingProgress/IndexingProgressIndicator.tsx
  gui/src/pages/config/IndexingProgress/IndexingProgressSubtext.tsx
  gui/src/pages/config/IndexingProgress/IndexingProgressTitleText.tsx
Labels: lgtm, size:L

#6594 Qwen3 support for autocomplete function
  core/autocomplete/postprocessing/index.ts
  core/package-lock.json
  docs/customize/deep-dives/autocomplete.mdx
  extensions/vscode/package-lock.json
  gui/package-lock.json
  packages/config-yaml/package-lock.json
  packages/openai-adapters/package-lock.json
Labels: lgtm, size:M

#6489 [QoL] Add Collapse Button to Sidebar History Panel (#6222)
  gui/src/components/History/index.tsx
Labels: lgtm, size:L

#6605 chore: add telemetry to config loading
  core/config/ConfigHandler.ts
  core/package-lock.json
  extensions/vscode/package-lock.json
  gui/package-lock.json
  packages/config-yaml/package-lock.json
  packages/openai-adapters/package-lock.json
Labels: lgtm, size:S

#6615 docs: remove unnecessary anchor tags
  docs/customization/mcp-tools.mdx
  docs/customization/models.mdx
  docs/customization/overview.mdx
  docs/customization/prompts.mdx
  docs/customization/rules.mdx
  docs/customize/custom-providers.mdx
  docs/customize/overview.mdx
  docs/customize/telemetry.mdx
  docs/features/agent/how-it-works.mdx
  docs/features/agent/quick-start.mdx
  docs/features/autocomplete/how-it-works.mdx
  docs/features/autocomplete/quick-start.mdx
  docs/features/chat/how-it-works.mdx
  docs/features/chat/quick-start.mdx
  docs/features/edit/quick-start.mdx
  docs/guides/build-your-own-context-provider.mdx
  docs/guides/custom-code-rag.mdx
  docs/guides/how-to-self-host-a-model.mdx
  docs/guides/llama3.1.mdx
  docs/guides/ollama-guide.mdx
  docs/guides/overview.mdx
  docs/hub/assistants/create-an-assistant.mdx
  docs/hub/blocks/block-types.mdx
  docs/hub/blocks/bundles.mdx
  docs/hub/blocks/create-a-block.mdx
  docs/hub/governance/pricing.mdx
  docs/hub/secrets/secret-types.mdx
  docs/hub/sharing.mdx
  docs/hub/source-control.mdx
  docs/reference.mdx
  docs/reference/json-reference.mdx
  docs/reference/yaml-migration.mdx
  docs/troubleshooting.mdx
Labels: lgtm, size:L

#6618 improv: make headers sticky
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/index.tsx
Labels: lgtm, size:XS

#6623 Update package.json
  extensions/vscode/package.json
Labels: size:XS

#6636 test: disable failing JB inline edit test (timeout bug)
  extensions/intellij/src/test/kotlin/com/github/continuedev/continueintellijextension/e2e/InlineEdit.kt
Labels: size:XS

#6589 enhancement: Improve Next Edit DX
  core/codeRenderer/CodeRenderer.ts
  core/diff/myers.ts
  core/diff/myers.vitest.ts
  core/diff/streamDiff.ts
  core/diff/streamDiff.vitest.ts
  core/index.d.ts
  core/nextEdit/constants.ts
  extensions/vscode/src/activation/NextEditWindowManager.ts
Labels: lgtm, size:XXL

#6585 fix: Return the CLA
  .github/workflows/cla.yaml
  CLA.md
Labels: lgtm, size:M

#6512 Fix: add sanitizing process to strip off the trailing slash of the doc URL
  core/indexing/docs/DocsCache.ts
Labels: lgtm, size:S

#6535 Suppress stderr output from Windows registry queries
  core/control-plane/mdm/mdm.ts
Labels: size:S

#6575 test: Remove flaky test
  extensions/intellij/src/test/kotlin/com/github/continuedev/continueintellijextension/unit/ContinueProcessHandlerTest.kt
Labels: lgtm, size:M

#6663 Simplify Edit Logging
  core/config/sharedConfig.ts
  core/index.d.ts
  extensions/vscode/package-lock.json
  extensions/vscode/src/util/editLoggingUtils.ts
  gui/src/pages/config/ContinueFeaturesMenu.tsx
  gui/src/pages/config/UserSettingsForm.tsx
Labels: lgtm, size:M

#6625 Nate/continue-proxy-openai-adapter
  core/package-lock.json
  core/package.json
  packages/openai-adapters/package-lock.json
  packages/openai-adapters/package.json
  packages/openai-adapters/src/apis/Bedrock.ts
  packages/openai-adapters/src/apis/ContinueProxy.ts
  packages/openai-adapters/src/apis/Gemini.ts
  packages/openai-adapters/src/apis/OpenAI.ts
  packages/openai-adapters/src/index.ts
  packages/openai-adapters/src/types.ts
Labels: lgtm, size:L

#6596 feat: :sparkles: Introduce LLM streamChat retries
  core/jest.config.js
  core/llm/llms/Bedrock.ts
  core/llm/utils/getSecureID.test.ts
  core/llm/utils/retry.test.ts
  core/llm/utils/retry.ts
  core/tsconfig.json
Labels: lgtm, size:XL

#6670 chore: bump versions
  extensions/intellij/gradle.properties
  extensions/vscode/package.json
Labels: size:XS

#6673 fix: don't use continue proxy openai adapter locally
  core/llm/llms/stubs/ContinueProxy.ts
  extensions/vscode/package.json
Labels: size:XS

#6664 fix: race condition for this.lanceDbIndex being loaded and retrieveEmbeddings accessing it
  core/context/retrieval/pipelines/BaseRetrievalPipeline.ts
Labels: size:S

#6669 chore: use icon for generate rule action
  gui/src/components/StepContainer/ResponseActions.tsx
Labels: size:S

#6684 Tomasz/fix sticky
  gui/src/components/StepContainer/StepContainer.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/index.tsx
Labels: lgtm, size:XS

#6662 feat: compaction
  core/core.ts
  core/index.d.ts
  core/protocol/core.ts
  core/protocol/passThrough.ts
  core/util/conversationCompaction.ts
  core/util/history.ts
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt
  extensions/vscode/e2e/README.md
  extensions/vscode/e2e/TestUtils.ts
  extensions/vscode/e2e/actions/NextEdit.actions.ts
  extensions/vscode/e2e/selectors/GUI.selectors.ts
  extensions/vscode/e2e/selectors/NextEdit.selectors.ts
  extensions/vscode/e2e/tests/GUI.test.ts
  extensions/vscode/e2e/tests/NextEdit.test.ts
  gui/src/components/Layout.tsx
  gui/src/components/StepContainer/ConversationSummary.tsx
  gui/src/components/StepContainer/ResponseActions.tsx
  gui/src/components/StepContainer/StepContainer.tsx
  gui/src/pages/gui/Chat.tsx
  gui/src/redux/slices/sessionSlice.test.ts
  gui/src/redux/slices/sessionSlice.ts
  gui/src/redux/util/constructMessages.ts
  packages/config-yaml/CHANGELOG.md
  packages/continue-sdk/typescript/src/createOpenAIClient.ts
Labels: lgtm, size:XL

#6686 openai adapters tests
  .github/workflows/pr_checks.yaml
  core/.eslintrc.json
  core/indexing/docs/crawlers/DocsCrawler.test.ts
  core/llm/llms/Anthropic.vitest.ts
  core/llm/llms/Docker.ts
  core/llm/llms/Fireworks.ts
  core/llm/llms/Fireworks.vitest.ts
  core/llm/llms/Groq.vitest.ts
  core/llm/llms/Kindo.ts
  core/llm/llms/NCompass.ts
  core/llm/llms/OpenAI-compatible-core.vitest.ts
  core/llm/llms/OpenAI-compatible.vitest.ts
  core/llm/llms/OpenAI.vitest.ts
  core/llm/llms/Venice.ts
  core/llm/llms/llmTestHarness.ts
  core/llm/llms/stubs/ContinueProxy.vitest.ts
  core/llm/llms/test-utils/openai-test-utils.ts
  core/package-lock.json
  package-lock.json
  packages/openai-adapters/package-lock.json
  packages/openai-adapters/package.json
  packages/openai-adapters/src/test/adapter-test-utils.ts
  packages/openai-adapters/src/test/anthropic-adapter.vitest.ts
  packages/openai-adapters/src/test/openai-adapter.vitest.ts
  packages/openai-adapters/vitest.config.ts
Labels: size:XXL

#6688 chore: bump verssions
  extensions/intellij/gradle.properties
  extensions/vscode/package.json
Labels: lgtm, size:XS

#6238 return usage from Anthropic OpenAI adapter
  core/index.d.ts
  core/llm/index.ts
  core/llm/llms/Anthropic.ts
  core/llm/logFormatter.test.ts
  core/llm/utils/calculateRequestCost.ts
  gui/src/components/console/Details.tsx
  gui/src/components/console/Layout.tsx
  gui/src/components/console/TotalUsage.tsx
  gui/src/console.tsx
  gui/src/hooks/useLLMSummary.ts
  gui/src/hooks/useTotalUsage.ts
  packages/openai-adapters/src/apis/Anthropic.ts
  packages/openai-adapters/src/test/main.test.ts
  packages/openai-adapters/src/test/util.ts
  packages/openai-adapters/src/util.ts
Labels: lgtm, size:XL

#6694 test: add voyage api key and run oai tests in pr checks
  .github/workflows/pr_checks.yaml
  .github/workflows/release-config-yaml.yml
  .github/workflows/release-fetch.yml
  .github/workflows/release-openai-adapters.yml
  .github/workflows/reusable-release.yml
  packages/openai-adapters/src/test/main.test.ts
  packages/openai-adapters/src/test/util.ts
Labels: size:L

#6679 fix: restore invalid config error reporting
  packages/config-yaml/src/load/unroll.test.ts
  packages/config-yaml/src/load/unroll.ts
Labels: lgtm, size:L

#6704 fix: allow prompts starting with `/`
  gui/src/components/mainInput/TipTapEditor/extensions/SlashCommand.ts
Labels: lgtm, size:XS

#6703 fix: remove reject edit diff functionality on cmd backspace
  gui/src/pages/gui/Chat.tsx
Labels: lgtm, size:XS

#6668 Context limit and pruning updates
  core/index.d.ts
  core/llm/countTokens.ts
  core/llm/index.ts
  gui/src/components/StepContainer/StepContainer.tsx
  gui/src/components/mainInput/ContextStatus.tsx
  gui/src/components/mainInput/ContinueInputBox.tsx
  gui/src/components/mainInput/InlineErrorMessage.tsx
  gui/src/components/mainInput/InputToolbar.tsx
  gui/src/components/mainInput/WarningMessageBox/Actions/EditConfigAction.tsx
  gui/src/components/mainInput/WarningMessageBox/Actions/NewSessionAction.tsx
  gui/src/components/mainInput/WarningMessageBox/ExpendableBox.tsx
  gui/src/components/mainInput/WarningMessageBox/index.tsx
  gui/src/components/modelSelection/ModelSelect.tsx
  gui/src/context/MockIdeMessenger.ts
  gui/src/pages/gui/Chat.tsx
  gui/src/redux/slices/sessionSlice.ts
  gui/src/redux/thunks/streamNormalInput.ts
  packages/shared-release.config.js
Labels: lgtm, size:L

#6709 Tomasz/compaction button UI
  gui/src/components/StepContainer/ConversationSummary.tsx
  gui/src/components/StepContainer/ResponseActions.tsx
  gui/src/components/mainInput/ContextStatus.tsx
  gui/src/redux/slices/sessionSlice.ts
  gui/src/util/compactConversation.ts
Labels: size:L

#6712 feat: Pause -> Stop
  gui/src/components/mainInput/Lump/LumpToolbar/StreamingToolbar.tsx
Labels: size:XS

#6572 docs: accessKeyId and secretAccessKey bedrock auth options
  docs/customize/model-providers/top-level/bedrock.mdx
Labels: size:M

#6733 Fix misformatted yaml code
  docs/customize/custom-providers.mdx
  docs/guides/custom-code-rag.mdx
  docs/guides/how-to-self-host-a-model.mdx
  docs/guides/llama3.1.mdx
  docs/guides/ollama-guide.mdx
  docs/guides/set-up-codestral.mdx
  docs/reference.mdx
  docs/reference/yaml-migration.mdx
  docs/troubleshooting.mdx
Labels: lgtm, size:L

#6531 fix: Follow JetBrains IDE proxy settings
  extensions/intellij/build.gradle.kts
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/auth/ContinueAuthService.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/ContinueExtensionSettingsService.kt
Labels: size:L

#6576 fix: Ignore invalid JSON messages (like NODE_ENV undefined)
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessenger.kt
Labels: lgtm, size:S

#6650 fix: internal permalinks with file extensions
  docs/customize/context/codebase.mdx
  docs/customize/context/documentation.mdx
  docs/customize/deep-dives/slash-commands.mdx
  docs/customize/model-roles/embeddings.mdx
Labels: lgtm, size:S

#6682 docs: Fix Codestral autocomplete setup - Azure AI Foundry FIM endpoin…
  docs/customize/model-providers/top-level/azure.mdx
Labels: lgtm, size:XS

#6678 chore: remove YAML maxDepth
  core/config/yaml/loadYaml.ts
  docs/customize/context/documentation.mdx
  docs/reference.mdx
  packages/config-yaml/src/schemas/index.ts
Labels: lgtm, size:XS

#6741 docs: update continue-mcp.mdx to mention new mcp server
  docs/reference/continue-mcp.mdx
Labels: lgtm, size:L

#6753 adjust best model reccs
  docs/features/chat/model-setup.mdx
Labels: lgtm, size:M

#6758 build: Fix jetbrains-release/bump-version CI job
  .github/workflows/jetbrains-release.yaml
Labels: size:XS

#6770 chore: upgrade
  extensions/intellij/gradle.properties
  extensions/vscode/package.json
Labels: lgtm, size:XS

#6553 fix: Send the process exit reason to Sentry + add OS info
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/process/ContinueBinaryProcess.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/error/ContinueErrorService.kt
Labels: lgtm, size:S

#6331 fix: :bug: Fix bare markdown fences and premature code generation stops
  core/autocomplete/filtering/streamTransforms/filterCodeBlock.ts
  core/autocomplete/filtering/streamTransforms/filterCodeBlock.vitest.ts
  core/autocomplete/filtering/streamTransforms/lineStream.ts
  core/autocomplete/filtering/streamTransforms/lineStream.vitest.ts
  core/edit/lazy/replace.ts
  core/edit/lazy/streamLazyApply.test.ts
  core/edit/lazy/streamLazyApply.ts
  core/edit/recursiveStream.ts
  core/edit/streamDiffLines.ts
  core/utils/markdownUtils.ts
  core/utils/markdownUtils.vitest.ts
  core/utils/streamMarkdownUtils.ts
  core/utils/streamMarkdownUtils.vitest.ts
  gui/src/components/StyledMarkdownPreview/utils/headerIsMarkdown.test.ts
  gui/src/components/StyledMarkdownPreview/utils/headerIsMarkdown.ts
  gui/src/components/StyledMarkdownPreview/utils/patchNestedMarkdown.test.ts
  gui/src/components/StyledMarkdownPreview/utils/patchNestedMarkdown.ts
Labels: lgtm, size:XXL

#6775 fix: missing `alwaysApply` in local rule block
  core/config/yaml/loadYaml.ts
Labels: lgtm, size:XS

#6784 fix: use loading state for loading indicator, better error messages
  core/config/ConfigHandler.ts
  gui/src/components/modelSelection/ModelSelect.tsx
  gui/src/redux/slices/configSlice.ts
Labels: lgtm, size:S

#6736 feat: vertex ai openai adapter
  core/llm/llms/Anthropic.ts
  core/llm/llms/Gemini.ts
  core/llm/llms/Mistral.ts
  core/llm/llms/VertexAI.ts
  core/llm/toolSupport.ts
  packages/openai-adapters/package-lock.json
  packages/openai-adapters/package.json
  packages/openai-adapters/src/apis/Anthropic.ts
  packages/openai-adapters/src/apis/Gemini.ts
  packages/openai-adapters/src/apis/VertexAI.ts
  packages/openai-adapters/src/index.ts
  packages/openai-adapters/src/types.ts
Labels: lgtm, size:XL

#6783 feat: create `oneper` util script
  .github/workflows/pr_checks.yaml
  scripts/oneper
Labels: lgtm, size:L

#6799 fix: fix /auth/refresh string value
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/auth/ContinueAuthService.kt
Labels: size:XS

#6720 fix: default pruning length higher than default context length
  core/llm/constants.ts
  core/llm/countTokens.ts
  core/llm/index.ts
  core/llm/llms/HuggingFaceTGI.ts
  core/llm/llms/Ollama.ts
  core/llm/llms/Vllm.ts
  core/util/generateRepoMap.test.ts
Labels: lgtm, size:M

#6794 feat: add word break for long words
  gui/src/components/StyledMarkdownPreview/index.tsx
Labels: lgtm, size:XS

#6793 fix: use reasoning budget tokens when available
  gui/src/redux/thunks/streamNormalInput.ts
Labels: lgtm, size:XS

#6805 chore: bump oai-adapters version
  packages/openai-adapters/package-lock.json
  packages/openai-adapters/package.json
Labels: size:XS

#6658 fix: Add logging of Continue binary IO
  extensions/intellij/CONTRIBUTING.md
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/process/ContinueProcessHandler.kt
Labels: size:S

#6788 feat: enhance oneper utility and refactor build system for commit SHA versioning
  .github/workflows/build-vscode-extension.yml
  .github/workflows/main-build.yaml
  .github/workflows/main.yaml
  .github/workflows/pr_checks.yaml
  .github/workflows/preview.yaml
  .vscode/launch.json
  .vscode/tasks.json
  core/jest.config.js
  core/llm/utils/retry.test.ts
  core/llm/utils/retry.ts
  core/package-lock.json
  core/package.json
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  gui/package-lock.json
  package-lock.json
  packages/config-types/src/index.ts
  packages/config-yaml/package-lock.json
  packages/config-yaml/package.json
  packages/continue-sdk/package-lock.json
  packages/continue-sdk/package.json
  packages/fetch/package-lock.json
  packages/fetch/package.json
  packages/llm-info/src/providers/gemini.ts
  packages/openai-adapters/package-lock.json
  packages/openai-adapters/package.json
  scripts/build-packages.ps1
  scripts/build-packages.sh
  scripts/install-dependencies.ps1
  scripts/install-dependencies.sh
  scripts/oneper
Labels: lgtm, size:XXL

#6751 test: verify chunkDocument filters out chunks exceeding maxChunkSize
  core/indexing/chunk/chunk.test.ts
  core/indexing/chunk/chunk.ts
  core/llm/countTokens.test.ts
  core/llm/countTokens.ts
Labels: lgtm, size:L

#6667 chore: update bug_report.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: lgtm, size:XS

#6808 chore: bump versions for prerelease
  extensions/intellij/gradle.properties
  extensions/vscode/package.json
Labels: lgtm, size:XS

#6811 Revert "feat: enhance oneper utility and refactor build system for commit SHA versioning"
  .github/workflows/build-vscode-extension.yml
  .github/workflows/main-build.yaml
  .github/workflows/main.yaml
  .github/workflows/pr_checks.yaml
  .github/workflows/preview.yaml
  .vscode/launch.json
  .vscode/tasks.json
  core/jest.config.js
  core/llm/utils/retry.test.ts
  core/llm/utils/retry.ts
  core/package-lock.json
  core/package.json
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  gui/package-lock.json
  package-lock.json
  packages/config-types/src/index.ts
  packages/config-yaml/package-lock.json
  packages/config-yaml/package.json
  packages/continue-sdk/package-lock.json
  packages/continue-sdk/package.json
  packages/fetch/package-lock.json
  packages/fetch/package.json
  packages/llm-info/src/providers/gemini.ts
  packages/openai-adapters/package-lock.json
  packages/openai-adapters/package.json
  scripts/build-packages.ps1
  scripts/build-packages.sh
  scripts/install-dependencies.ps1
  scripts/install-dependencies.sh
  scripts/oneper
Labels: lgtm, size:XXL

#6710 chore: add unit tests for file click on codeblock
  gui/src/components/mainInput/TipTapEditor/extensions/CodeBlock/CodeBlockPreview.test.tsx
  gui/src/components/mainInput/TipTapEditor/extensions/CodeBlock/CodeBlockPreview.tsx
Labels: lgtm, size:M

#6825 chore: ignore `max-lines-per-function` in tests
  core/.eslintrc.json
  extensions/vscode/package-lock.json
Labels: lgtm, size:XS

#6472 Modernize downloadFile function with fetch API and proxy support
  extensions/vscode/scripts/download-copy-sqlite-esbuild.js
Labels: lgtm, size:M

#6661 Jacob/enhancement/nextedit perf
  extensions/vscode/src/activation/NextEditWindowManager.ts
  extensions/vscode/src/autocomplete/completionProvider.ts
Labels: lgtm, size:L

#6666 fix: test fix for fetch package and publish version with improved error logging
  packages/fetch/package-lock.json
  packages/fetch/package.json
  packages/fetch/src/stream.test.ts
  packages/openai-adapters/package-lock.json
  packages/openai-adapters/package.json
Labels: lgtm, size:XS

#6827 Add Ollama OpenAI adapter support
  packages/openai-adapters/src/apis/Anthropic.ts
  packages/openai-adapters/src/apis/OpenAI.ts
  packages/openai-adapters/src/index.ts
  packages/openai-adapters/src/types.ts
Labels: size:S

#6614 Revert "remove accountbutton"
  gui/src/components/AssistantAndOrgListbox/AccountOption.tsx
  gui/src/components/AssistantAndOrgListbox/index.tsx
  gui/src/pages/config/AccountButton.tsx
  gui/src/pages/config/index.tsx
  gui/src/pages/history/index.tsx
Labels: lgtm, size:L

#6838 Nate/oneper-main
  .github/workflows/auto-release.yml
  .github/workflows/main-build.yaml
  .github/workflows/vscode-version-bump.yml
  package-lock.json
  scripts/oneper
Labels: lgtm, size:L

#6841 System message tools by default for OpenRouter
  core/config/shouldAutoEnableSystemMessageTools.ts
  core/config/shouldAutoEnableSystemMessageTools.vitest.ts
  core/llm/llm.test.ts
  core/llm/llms/OpenAI.vitest.ts
  extensions/vscode/e2e/tests/NextEdit.skip.ts
  gui/src/components/ModeSelect/ModeSelect.tsx
  gui/src/redux/selectors/selectUseSystemMessageTools.test.ts
  gui/src/redux/selectors/selectUseSystemMessageTools.ts
  gui/src/redux/thunks/streamNormalInput.ts
Labels: lgtm, size:L

#6848 Bump version to 1.1.70
  extensions/vscode/package.json
Labels: size:XS

#6854 chore: bump to 71
  extensions/vscode/package.json
Labels: size:XS

#6850 fix: :bug: Use login shell and powershell
  core/tools/definitions/runTerminalCommand.ts
  core/tools/implementations/runTerminalCommand.ts
Labels: lgtm, size:M

#6839 feat: restore enhanced build system and integrate parallel build script
  .github/actions/build-vscode-extension/action.yml
  .github/actions/run-jetbrains-tests/action.yml
  .github/actions/run-vscode-e2e-test/action.yml
  .github/actions/setup-component/action.yml
  .github/actions/setup-packages/action.yml
  .github/workflows/compliance.yaml
  .github/workflows/jetbrains-release.yaml
  .github/workflows/main.yaml
  .github/workflows/pr-build-upload-vsix.yaml
  .github/workflows/pr-checks.yaml
  .github/workflows/pr_checks.yaml
  .github/workflows/preview.yaml
  .vscode/launch.json
  .vscode/tasks.json
  core/jest.config.js
  core/llm/utils/retry.test.ts
  core/llm/utils/retry.ts
  core/package-lock.json
  core/package.json
  extensions/vscode/e2e/tests/NextEdit.skip.ts
  extensions/vscode/e2e/tests/NextEdit.test.skip.ts
  extensions/vscode/e2e/tests/SSH.skip.ts
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  extensions/vscode/scripts/prepackage.js
  gui/package-lock.json
  packages/config-types/package.json
  packages/config-types/src/index.ts
  packages/config-yaml/package-lock.json
  packages/config-yaml/package.json
  packages/continue-sdk/package-lock.json
  packages/continue-sdk/package.json
  packages/fetch/package-lock.json
  packages/fetch/package.json
  packages/hub/package.json
  packages/llm-info/package.json
  packages/llm-info/src/providers/gemini.ts
  packages/openai-adapters/package-lock.json
  packages/openai-adapters/package.json
  packages/openai-adapters/src/test/main.test.ts
  scripts/build-packages.js
  scripts/build-packages.ps1
  scripts/build-packages.sh
  scripts/install-dependencies.ps1
  scripts/install-dependencies.sh
  scripts/oneper
Labels: size:XXL

#6451 Add second check for prompt length before autocomplete
  core/autocomplete/CompletionProvider.ts
  core/autocomplete/templating/__tests__/renderPrompt.vitest.ts
  core/autocomplete/templating/index.ts
  core/llm/countTokens.ts
Labels: size:XL

#6560 Add retry logic with exponential backoff to listOrganizations for user account creation delay
  core/control-plane/client.ts
Labels: size:M

#6877 docs: fix broken Docs deep dive link
  docs/hub/blocks/block-types.mdx
Labels: lgtm, size:XS

#6878 docs: fix broken links in the customization overview page
  docs/customization/overview.mdx
Labels: size:XS

#6894 fix: apply Sentry and PostHog telemetry settings correctly
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/auth/ContinueAuthService.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessengerManager.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/process/ContinueBinaryProcess.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/process/ContinueProcessHandler.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/error/ContinueErrorSubmitter.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/error/ContinuePostHogService.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/error/ContinueSentryService.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/error/ContinueTelemetryStatus.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/error/ContinueTelemetryStatusService.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/ContinueExtensionSettingsService.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/TelemetryService.kt
  extensions/intellij/src/test/kotlin/com/github/continuedev/continueintellijextension/unit/ContinuePostHogServiceTest.kt
Labels: size:L
