Repository continuedev/continue, pull requests merged in 2025-06, with the labels that each got.

#5310 perf(llm): Optimize pruneLines functions in countTokens
  core/llm/countTokens.test.ts
  core/llm/countTokens.ts
Labels: lgtm, size:L

#5851 Fix Config.yaml schema registration
  extensions/vscode/src/activation/activate.ts
Labels: lgtm, size:M

#5874 fix changing width when typing text
  gui/src/components/mainInput/TipTapEditor/TipTapEditor.css
Labels: lgtm, size:XS

#5891 Add JCEF out of process vm setting
  extensions/intellij/.run/Run Extension.run.xml
  extensions/intellij/.run/Run Qodana.run.xml
  extensions/intellij/.run/Run Test IDE.run.xml
  extensions/intellij/.run/Run Tests.run.xml
Labels: lgtm, size:XS

#5925 fix: mac build issues
  extensions/vscode/scripts/prepackage.js
Labels: lgtm, size:XS

#5461 fetch secrets from <workspace>/.continue/.env folder before <workspace>/.env
  .github/workflows/pr_checks.yaml
  core/config/yaml/LocalPlatformClient.test.ts
  core/config/yaml/LocalPlatformClient.ts
  core/jest.config.js
  core/package-lock.json
  core/package.json
  core/vitest.config.ts
Labels: lgtm, size:L

#5612 Nate/fix-openai-adapters
  packages/openai-adapters/src/apis/DeepSeek.ts
  packages/openai-adapters/src/apis/Inception.ts
  packages/openai-adapters/src/test/main.test.ts
Labels: lgtm, size:M

#5967 feat: add `no-negated-condition` eslint
  .eslintrc.shared.json
Labels: lgtm, size:XS

#5946 Prompts fixes
  core/config/yaml/LocalPlatformClient.vitest.ts
  core/context/providers/URLContextProvider.ts
  core/promptFiles/v1/slashCommandFromPromptFile.ts
  core/promptFiles/v2/renderPromptFile.ts
  core/promptFiles/v2/renderPromptFile.vitest.ts
  core/vitest.config.ts
  gui/src/components/mainInput/TipTapEditor/components/ExpandableToolbarPreview.tsx
  gui/src/components/mainInput/TipTapEditor/extensions/Prompt/PromptBlock.ts
  gui/src/components/mainInput/TipTapEditor/extensions/Prompt/PromptBlockPreview.tsx
  gui/src/components/mainInput/TipTapEditor/utils/resolveEditorContent.ts
Labels: lgtm, size:L

#5983 Only allow completions through continue for vllm for now
  core/llm/llms/stubs/ContinueProxy.ts
Labels: lgtm, size:XS

#5813 feat: :bricks: Enable terminals for additional vscode Remote Host Types
  core/tools/implementations/runTerminalCommand.ts
Labels: lgtm, size:XS

#5905 Delete docs/docs/customize/tutorials/build-your-own-slash-command.md
  docs/docs/customize/deep-dives/configuration.md
  docs/docs/customize/tutorials/build-your-own-slash-command.md
  docs/docs/json-reference.md
Labels: lgtm, size:M

#5976 Gemini LLM Info
  .continue/prompts/update-llm-info.prompt
  packages/llm-info/package-lock.json
  packages/llm-info/package.json
  packages/llm-info/src/providers/gemini.ts
Labels: lgtm, size:L

#5994 fix: linting error
  core/tools/implementations/runTerminalCommand.ts
Labels: lgtm, size:S

#5993 fix: :bug: Codebase indexing is not starting on load
  core/core.ts
Labels: lgtm, size:XS

#6014 streamable-http support in YAML
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  gui/package-lock.json
  packages/config-yaml/src/schemas/index.ts
Labels: size:XS

#5944 Better notch rules section border
  gui/src/components/mainInput/Lump/sections/RulesSection.tsx
Labels: lgtm, size:S

#5990 Bubble up config and block errors to the extension GUI
  core/config/yaml/loadYaml.ts
  extensions/vscode/package-lock.json
  gui/src/components/mainInput/Lump/sections/errors/ErrorSection.tsx
  packages/config-yaml/src/load/unroll.ts
Labels: lgtm, size:L

#6024 feat: skip hub onboarding in free trial
  extensions/vscode/src/stubs/WorkOsAuthProvider.ts
  gui/src/components/ModeSelect/ModeSelect.tsx
  gui/src/components/OnboardingCard/platform/tabs/main.tsx
  gui/src/components/PageHeader.tsx
  gui/src/components/dialogs/ConfirmationDialog.tsx
  gui/src/components/index.ts
  gui/src/components/ui/Button.tsx
  gui/src/components/ui/Listbox.tsx
  gui/src/pages/config/AccountButton.tsx
  gui/src/pages/config/KeyboardShortcuts.tsx
Labels: lgtm, size:L

#6029 Fix tool call name merging
  gui/src/util/toolCallState.test.ts
  gui/src/util/toolCallState.ts
Labels: lgtm, size:L

#6023 feat: use correct deployment for azure
  .github/workflows/pr_checks.yaml
  packages/openai-adapters/src/apis/Azure.ts
  packages/openai-adapters/src/apis/OpenAI.ts
  packages/openai-adapters/src/index.ts
  packages/openai-adapters/src/test/main.test.ts
  packages/openai-adapters/src/test/util.ts
  packages/openai-adapters/src/types.ts
  packages/openai-adapters/tsconfig.json
Labels: size:L

#6034 feat: refactor onboarding card
  .continue/rules/gui-link-opening.md
  core/config/onboarding.ts
  core/core.ts
  core/core_temp.ts
  core/index.d.ts
  core/protocol/core.ts
  core/protocol/passThrough.ts
  docs/docs/customize/model-roles/apply.mdx
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt
  extensions/vscode/package.json
  extensions/vscode/src/stubs/WorkOsAuthProvider.ts
  gui/package-lock.json
  gui/src/components/AddModelButtonSubtext.tsx
  gui/src/components/Layout.tsx
  gui/src/components/OnboardingCard/OnboardingCard.tsx
  gui/src/components/OnboardingCard/components/BestExperienceConfigForm.tsx
  gui/src/components/OnboardingCard/components/OllamaModelDownload.tsx
  gui/src/components/OnboardingCard/components/OnboardingCardLanding.tsx
  gui/src/components/OnboardingCard/components/OnboardingCardTabs.tsx
  gui/src/components/OnboardingCard/components/OnboardingLocalTab.tsx
  gui/src/components/OnboardingCard/components/OnboardingProvidersTab.tsx
  gui/src/components/OnboardingCard/components/ProviderAlert.tsx
  gui/src/components/OnboardingCard/components/QuickStartSubmitButton.tsx
  gui/src/components/OnboardingCard/components/index.ts
  gui/src/components/OnboardingCard/hooks/useOnboardingCard.ts
  gui/src/components/OnboardingCard/hooks/useSubmitOnboarding.ts
  gui/src/components/OnboardingCard/platform/PlatformOnboardingCard.tsx
  gui/src/components/OnboardingCard/platform/tabs/main.tsx
  gui/src/components/OnboardingCard/tabs/OnboardingBestTab.tsx
  gui/src/components/OnboardingCard/tabs/OnboardingQuickstartTab.tsx
  gui/src/components/OnboardingCard/tabs/index.ts
  gui/src/components/OnboardingCard/utils.ts
  gui/src/components/dialogs/FreeTrialOverDialog.tsx
  gui/src/components/index.ts
  gui/src/components/loaders/FreeTrialProgressBar.tsx
  gui/src/components/mainInput/Lump/LumpToolbar/BlockSettingsTopToolbar.tsx
  gui/src/components/mainInput/Lump/sections/ModelsSection.tsx
  gui/src/components/modelSelection/ModelSelect.tsx
  gui/src/components/modelSelection/ModelSelectionListbox.tsx
  gui/src/components/modelSelection/platform/AssistantSelect.tsx
  gui/src/forms/AddModelForm.tsx
  gui/src/forms/index.ts
  gui/src/pages/config/HelpCenterSection.tsx
  gui/src/pages/config/ModelRoleSelector.tsx
  gui/src/pages/gui/Chat.tsx
  gui/src/pages/gui/EmptyChatBody.tsx
  gui/src/redux/slices/configSlice.ts
  gui/src/redux/thunks/selectFirstHubProfile.ts
Labels: size:XXL

#5995 Handle JSON Parsing errors
  core/__mocks__/@continuedev/fetch/index.ts
  core/context/providers/GoogleContextProvider.ts
  core/context/providers/GreptileContextProvider.ts
  core/core.ts
  core/indexing/LanceDbIndex.ts
  core/llm/llm-pre-fetch.vitest.ts
  core/llm/llms/Anthropic.ts
  core/llm/llms/Bedrock.ts
  core/llm/llms/BedrockImport.ts
  core/llm/llms/Gemini.ts
  core/llm/llms/HuggingFaceTEI.ts
  core/llm/llms/SageMaker.ts
  core/llm/openaiTypeConverters.ts
  core/tools/callTool.ts
  core/tools/parseArgs.ts
  gui/src/redux/thunks/callCurrentTool.ts
  gui/src/util/clientTools/callClientTool.ts
  packages/fetch/src/stream.ts
  packages/openai-adapters/src/apis/Anthropic.ts
  packages/openai-adapters/src/apis/Gemini.ts
  packages/openai-adapters/src/util/parseArgs.ts
Labels: lgtm, size:L

#5945 feat: create markdown rules in notch
  core/config/markdown/createMarkdownRule.test.ts
  core/config/markdown/createMarkdownRule.ts
  core/config/markdown/index.ts
  core/config/workspace/workspaceBlocks.test.ts
  core/config/workspace/workspaceBlocks.ts
  core/tools/definitions/createRuleBlock.ts
  core/tools/implementations/createRuleBlock.test.ts
  core/tools/implementations/createRuleBlock.ts
  gui/src/components/mainInput/Lump/sections/ExploreBlocksButton.tsx
  gui/src/components/mainInput/Lump/sections/RulesSection.tsx
Labels: lgtm, size:XL

#6004 feat(scaleway): update supported models
  core/llm/llms/Scaleway.ts
Labels: size:XS

#6050 docs: 📜 Update prompt caching docs for AWS Bedrock
  docs/docs/customize/model-providers/top-level/bedrock.mdx
  docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/customize/model-providers/top-level/bedrock.md
Labels: lgtm, size:M

#6058 fix: apply notch filename trunaction
  gui/src/components/AcceptRejectDiffButtons.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/ApplyActions.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/index.tsx
  gui/src/components/mainInput/Lump/LumpToolbar/PendingApplyStatesToolbar.tsx
Labels: lgtm, size:S

#6057 ignore running tests inside dist directory
  packages/config-yaml/jest.config.mjs
Labels: lgtm, size:XS

#6071 fix: handle apiType for azure w/ proxy
  core/llm/llms/stubs/ContinueProxy.ts
  packages/openai-adapters/package.json
  packages/openai-adapters/src/apis/Azure.ts
Labels: lgtm, size:S

#6070 RulesContextProvider
  core/config/profile/doLoadConfig.ts
  core/context/providers/RulesContextProvider.ts
  core/context/providers/index.ts
  extensions/vscode/package-lock.json
  gui/src/components/mainInput/AtMentionDropdown/index.tsx
  gui/src/components/mainInput/icons.ts
Labels: lgtm, size:L

#6072 bump
  extensions/vscode/package.json
Labels: size:XS

#6073 Update extension name
  extensions/vscode/package.json
Labels: size:XS

#6048 Tomasz/rule colocation
  core/config/markdown/loadCodebaseRules.ts
  core/config/markdown/loadCodebaseRules.vitest.ts
  core/config/markdown/ruleCollocationApplication.vitest.ts
  core/config/profile/doLoadConfig.ts
  core/core.ts
  core/llm/rules/alwaysApplyRules.vitest.ts
  core/llm/rules/constants.ts
  core/llm/rules/fileProtocolMatching.vitest.ts
  core/llm/rules/getSystemMessageWithRules.test.ts
  core/llm/rules/getSystemMessageWithRules.ts
  core/llm/rules/getSystemMessageWithRules.vitest.ts
  core/llm/rules/implicitGlobalRules.vitest.ts
  core/llm/rules/nestedDirectoryRules.vitest.ts
  core/llm/rules/ruleColocation.vitest.ts
  core/package.json
  manual-testing-sandbox/nested-folder/rules.md
Labels: lgtm, size:XXL

#5812 feat: add `tools` in chatInteraction dev data
  core/data/log.test.ts
  gui/src/redux/thunks/streamNormalInput.ts
  packages/config-yaml/src/schemas/data/chatInteraction/index.ts
  packages/config-yaml/src/schemas/data/chatInteraction/v0.2.0.ts
Labels: lgtm, size:M

#6012 [Updated PR] [Feature] Autocomplete context from other tabs open in the editor
  core/autocomplete/snippets/getAllSnippets.ts
  core/autocomplete/templating/__tests__/formatOpenedFilesContext.test.ts
  core/autocomplete/templating/filtering.ts
  core/autocomplete/templating/formatOpenedFilesContext.ts
  core/autocomplete/templating/index.ts
  core/autocomplete/util/openedFilesLruCache.ts
  core/context/retrieval/pipelines/BaseRetrievalPipeline.ts
  core/context/retrieval/recentlyEditedFilesCache.ts
  core/core.ts
  core/index.d.ts
  core/protocol/messenger/messageIde.ts
  core/util/filesystem.ts
  core/util/parameters.ts
  extensions/vscode/src/VsCodeIde.ts
  extensions/vscode/src/extension/VsCodeExtension.ts
  extensions/vscode/src/util/ideUtils.ts
  manual-testing-sandbox/calculator_test/Calculator.java
  manual-testing-sandbox/calculator_test/Main.java
  manual-testing-sandbox/test.py
Labels: lgtm, size:XL

#6049 docs: markdown first rules
  docs/docs/agent/how-to-customize.md
  docs/docs/blocks/rules.md
  docs/docs/chat/how-to-customize.md
  docs/docs/customize/deep-dives/rules.mdx
  docs/docs/hub/blocks/block-types.md
  docs/docs/reference.md
Labels: lgtm, size:L

#6055 Simple Context Deduplication for Autocomplete
  core/autocomplete/templating/filtering.ts
  core/autocomplete/templating/formatOpenedFilesContext.ts
  core/autocomplete/templating/validation.ts
Labels: lgtm, size:M

#6085 Update contributing: add note to install vite
  CONTRIBUTING.md
Labels: lgtm, size:XS

#6102 docs: update rule properties
  docs/docs/customize/deep-dives/rules.mdx
Labels: lgtm, size:XS

#6028 feat: Add shortcut to force autocomplete (VSCode)
  binary/package-lock.json
  core/autocomplete/CompletionProvider.ts
  core/package-lock.json
  docs/docs/autocomplete/how-to-use-it.md
  extensions/vscode/e2e/actions/Autocomplete.actions.ts
  extensions/vscode/e2e/tests/Autocomplete.test.ts
  extensions/vscode/package.json
  extensions/vscode/src/autocomplete/completionProvider.ts
  extensions/vscode/src/commands.ts
  gui/src/pages/config/KeyboardShortcuts.tsx
Labels: lgtm, size:M

#5641 instructions to clean reset the plugin
  docs/docs/customize/model-roles/apply.mdx
  docs/docs/troubleshooting.mdx
Labels: lgtm, size:XS

#6122 chore: add no-misused-promises eslint rule
  .eslintrc.shared.json
  core/autocomplete/context/root-path-context/test/testUtils.ts
  core/config/ProfileLifecycleManager.ts
  core/core.ts
  core/indexing/LanceDbIndex.ts
  core/indexing/chunk/chunk.ts
  core/indexing/docs/DocsService.ts
  core/indexing/docs/migrations.ts
  extensions/vscode/.eslintrc.json
Labels: lgtm, size:L

#6104 vscode 1.1.48
  extensions/vscode/package.json
Labels: lgtm, size:XS

#6134 Jetbrains v1.0.23
  extensions/intellij/gradle.properties
Labels: lgtm, size:XS

#5954 feat: add support for vLLM response format in reranking logic and up…
  core/llm/index.ts
  core/llm/llms/Vllm.ts
  docs/docs/customize/model-providers/more/vllm.mdx
Labels: lgtm, size:M

#6097 feat: improve fatal error message
  core/config/yaml/loadYaml.ts
Labels: lgtm, size:S

#6063 chore: migrate core (autocomplete) tests to vitest
  core/autocomplete/context/root-path-context/test/RootPathContextService.vitest.ts
  core/autocomplete/context/root-path-context/test/testUtils.ts
  core/autocomplete/filtering/streamTransforms/charStream.vitest.ts
  core/autocomplete/filtering/streamTransforms/lineStream.vitest.ts
  core/autocomplete/filtering/test/filter.vitest.ts
  core/autocomplete/filtering/test/util.ts
  core/autocomplete/generation/GeneratorReuseManager.vitest.ts
  core/autocomplete/generation/ListenableGenerator.vitest.ts
  core/autocomplete/generation/utils.vitest.ts
  core/autocomplete/snippets/gitDiffCache.vitest.ts
  core/autocomplete/templating/__tests__/formatOpenedFilesContext.vitest.ts
  core/autocomplete/util/completionTestUtils.vitest.ts
  core/autocomplete/util/processSingleLineCompletion.vitest.ts
  core/config/yaml/LocalPlatformClient.vitest.ts
  core/jest.config.js
  core/test/vitest.global-setup.ts
  core/test/vitest.setup.ts
  core/util/treeSitter.ts
  core/vitest.config.ts
Labels: lgtm, size:L

#6171 fix vllm import in docs
  docs/docs/customize/model-providers/more/vllm.mdx
Labels: lgtm, size:XS

#6172 fix: failing azure llm test
  .github/workflows/pr_checks.yaml
  core/llm/llm.test.ts
Labels: lgtm, size:M

#6182 allow "unrolling" of markdown blocks
  packages/config-yaml/package-lock.json
  packages/config-yaml/package.json
  packages/config-yaml/src/load/unroll.ts
Labels: lgtm, size:XS

#6106 feat: add proxy support for ripgrep download
  binary/package-lock.json
  binary/package.json
  binary/utils/ripgrep.js
Labels: lgtm, size:XS

#6000 fix intellij extension create file failed
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/ApplyToFileHandler.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/EditorUtils.kt
Labels: lgtm, size:M

#6153 improve docs style guide
  .continue/rules/documentation-standards.md
Labels: lgtm, size:L

#6189 adds posthog-docusaurus
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
Labels: lgtm, size:XS

#6170 test: alwaysApply
  core/llm/rules/alwaysApply.vitest.ts
Labels: lgtm, size:L

#6147 change icon for grep search tool
  gui/src/pages/gui/ToolCallDiv/index.tsx
Labels: lgtm, size:XS

#6109 fix: :bug: Add requestOptions to YAML config for mcp
  packages/config-yaml/src/schemas/index.ts
Labels: lgtm, size:XS

#6206 Limit and Truncate Grep Search output
  core/config/types.ts
  core/context/providers/SearchContextProvider.ts
  core/index.d.ts
  core/protocol/ide.ts
  core/protocol/messenger/messageIde.ts
  core/protocol/messenger/reverseMessageIde.ts
  core/tools/definitions/grepSearch.ts
  core/tools/implementations/grepSearch.ts
  core/util/filesystem.ts
  core/util/grepSearch.ts
  core/util/grepSearch.vitest.ts
  docs/docs/agent/how-it-works.md
  docs/docs/customize/context-providers.mdx
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/protocol/ide.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/types.kt
  extensions/vscode/config_schema.json
  extensions/vscode/src/VsCodeIde.ts
  extensions/vscode/src/extension/VsCodeMessenger.ts
Labels: lgtm, size:L

#6208 Limit glob tool output
  core/index.d.ts
  core/protocol/ide.ts
  core/protocol/messenger/reverseMessageIde.ts
  core/tools/definitions/globSearch.ts
  core/tools/implementations/globSearch.ts
  core/util/filesystem.ts
  docs/docs/agent/how-it-works.md
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/protocol/ide.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/types.kt
  extensions/vscode/src/VsCodeIde.ts
  extensions/vscode/src/extension/VsCodeMessenger.ts
Labels: lgtm, size:M

#6231 bump openai-adapters
  packages/openai-adapters/package-lock.json
  packages/openai-adapters/package.json
Labels: lgtm, size:XS

#6068 improved error logging
  core/context/retrieval/pipelines/NoRerankerRetrievalPipeline.ts
  core/context/retrieval/pipelines/RerankerRetrievalPipeline.ts
  core/util/posthog.ts
Labels: lgtm, size:M

#6037 fix: Fix the issue where the chunk index might be duplicated
  core/indexing/chunk/chunk.ts
Labels: lgtm, size:XS

#6209 Some rules
  .continue/rules/navigating-responses.md
  .continue/rules/programming-principles.md
  .continue/rules/unit-testing-rules.yaml
  extensions/vscode/rules.md
Labels: lgtm, size:M

#6225 Handle empty query by sending "null" instead of empty string in MCP context provider
  core/context/providers/MCPContextProvider.ts
Labels: lgtm, size:XS

#6214 improve: increase default context length and add tests for detecting context length
  core/llm/constants.ts
  core/llm/index.test.ts
  core/llm/llms/Anthropic.ts
  core/llm/llms/Bedrock.ts
Labels: lgtm, size:M

#6187 fix: show assistant loading after login
  gui/src/components/AssistantAndOrgListbox/AssistantOptions.tsx
  gui/src/components/AssistantAndOrgListbox/SelectedAssistantButton.tsx
  gui/src/components/AssistantAndOrgListbox/index.tsx
  gui/src/context/Auth.tsx
  gui/src/hooks/ParallelListeners.tsx
  gui/src/redux/slices/configSlice.ts
Labels: lgtm, size:L

#6283 fetch 14 for core
  core/package-lock.json
  core/package.json
Labels: lgtm, size:XS

#6164 Fetch 14: Read node extra ca certs, better NO_PROXY logic
  packages/fetch/package.json
  packages/fetch/src/certs.test.ts
  packages/fetch/src/certs.ts
  packages/fetch/src/fetch.test.ts
  packages/fetch/src/fetch.ts
  packages/fetch/src/getAgentOptions.test.ts
  packages/fetch/src/getAgentOptions.ts
  packages/fetch/src/util.test.ts
  packages/fetch/src/util.ts
Labels: lgtm, size:XXL

#6271 fix: pass `env` obj to openai-adapters
  .github/workflows/pr_checks.yaml
  core/llm/index.ts
  core/package-lock.json
  core/package.json
  extensions/vscode/package-lock.json
  gui/package-lock.json
Labels: lgtm, size:M

#6251 log whether tool calls fail or succeed
  gui/src/redux/thunks/callCurrentTool.ts
Labels: lgtm, size:S

#6175 fix: maxEmbeddingBatchSize not being respected
  core/indexing/CodebaseIndexer.test.ts
  core/indexing/CodebaseIndexer.ts
  core/llm/llms/Bedrock.ts
  core/llm/llms/HuggingFaceTEI.ts
  core/llm/llms/SageMaker.ts
Labels: lgtm, size:M

#6286 chore: prerelease
  extensions/vscode/package.json
Labels: lgtm, size:XS

#6276 fix: skip ripgrep if workspace is remote
  core/config/yaml/loadYaml.ts
  core/index.d.ts
  core/protocol/ide.ts
  core/protocol/messenger/messageIde.ts
  core/tools/index.ts
  core/util/filesystem.ts
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/types.kt
  extensions/vscode/src/VsCodeIde.ts
  scripts/create-docker-ssh-container.sh
Labels: lgtm, size:M

#6296 fix: azure adapter
  core/package-lock.json
  core/package.json
  extensions/intellij/gradle.properties
  extensions/vscode/package.json
  packages/openai-adapters/package-lock.json
  packages/openai-adapters/package.json
  packages/openai-adapters/src/apis/Azure.ts
  packages/openai-adapters/src/test/main.test.ts
Labels: lgtm, size:M

#6298 chore: bump package-lock.json files
  binary/package-lock.json
  extensions/vscode/package-lock.json
  gui/package-lock.json
  packages/config-yaml/package-lock.json
Labels: lgtm, size:XS

#6300 build.sh and build.ps1 to build packages in CI
  .github/workflows/main.yaml
  build.ps1
  build.sh
  core/package-lock.json
  core/package.json
Labels: size:M

#6301 chore: update preview.yaml with package build logic
  .github/workflows/main.yaml
  .github/workflows/preview.yaml
  binary/package-lock.json
  extensions/vscode/package-lock.json
  gui/package-lock.json
  scripts/build-packages.ps1
  scripts/build-packages.sh
Labels: lgtm, size:S

#6302 chore: execute permission on build scripts
  scripts/build-packages.ps1
  scripts/build-packages.sh
Labels: size:XS

#6228 New .continue/rules
  .continue/rules/new-protocol-message.md
  .continue/rules/overeager.md
  core/rules.md
Labels: lgtm, size:M

#6314 Revert "Dev data: added tool usage event"
  gui/src/redux/slices/sessionSlice.ts
  packages/config-yaml/src/schemas/data/index.ts
  packages/config-yaml/src/schemas/data/toolUsage/index.ts
  packages/config-yaml/src/schemas/data/toolUsage/v0.2.0.ts
Labels: lgtm, size:M

#5866 Expand Edit Tool tests, fix auto-apply duplicate responses
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/index.tsx
  gui/src/components/StyledMarkdownPreview/index.tsx
  gui/src/components/mainInput/TipTapEditor/utils/editorConfig.ts
  gui/src/context/MockIdeMessenger.ts
  gui/src/hooks/ParallelListeners.tsx
  gui/src/pages/gui/Chat.test.tsx
  gui/src/pages/gui/ToolCallDiv/EditFile.tsx
  gui/src/pages/gui/chat-tests/ApplyScenarios.test.tsx
  gui/src/pages/gui/chat-tests/Chat.test.tsx
  gui/src/pages/gui/chat-tests/EditToolScenarios.test.tsx
  gui/src/redux/slices/sessionSlice.ts
  gui/src/redux/store.ts
  gui/src/redux/thunks/callCurrentTool.ts
  gui/src/redux/thunks/edit.ts
  gui/src/redux/thunks/streamNormalInput.ts
  gui/src/redux/thunks/streamResponseAfterToolCall.ts
  gui/src/redux/thunks/streamThunkWrapper.tsx
  gui/src/util/clientTools/callClientTool.ts
  gui/src/util/clientTools/editImpl.ts
  gui/src/util/test/config.ts
  gui/src/util/test/utils.ts
  gui/vite.config.ts
Labels: lgtm, size:XXL

#6310 fix: prevent focus out on mod backspace in chat area
  gui/src/pages/gui/Chat.tsx
  gui/src/util/index.ts
Labels: lgtm, size:S

#6022 chore: speedup builds for binary and prepackage
  .vscode/tasks.json
  binary/build.js
  binary/utils/bundle-binary.js
  extensions/vscode/.gitignore
  extensions/vscode/scripts/download-copy-sqlite-esbuild.js
  extensions/vscode/scripts/esbuild.js
  extensions/vscode/scripts/generate-copy-config.js
  extensions/vscode/scripts/install-copy-nodemodule.js
  extensions/vscode/scripts/npm-install.js
  extensions/vscode/scripts/prepackage.js
  extensions/vscode/scripts/utils.js
  scripts/install-dependencies.sh
Labels: size:XXL

#6312 Handle empty string json args
  core/tools/parseArgs.ts
  gui/src/components/console/ResultGroup.tsx
  packages/openai-adapters/src/util/parseArgs.ts
Labels: lgtm, size:S

#6174 Remove unused mocha test runner
  .vscode/launch.json
  .vscode/tasks.json
  extensions/vscode/.vscodeignore
  extensions/vscode/esbuild.test.mjs
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  extensions/vscode/src/test/runner/mochaRunner.ts
  extensions/vscode/src/test/runner/runTestOnVSCodeHost.ts
  extensions/vscode/src/test/test-suites/ideUtils.test.ts
Labels: lgtm, size:L

#6343 Update CONTRIBUTING.md
  extensions/intellij/CONTRIBUTING.md
Labels: lgtm, size:XS

#6330 New rule to enfore that EditAggregator is a singleton
  .continue/rules/edit-aggregator-singleton-rule.md
Labels: size:XS

#6313 Update bedrock.mdx
  docs/docs/customize/model-providers/top-level/bedrock.mdx
Labels: lgtm, size:S

#6349 Updates on Next Edit PR
  core/autocomplete/constants/AutocompleteLanguageInfo.ts
  core/codeRenderer/CodeRenderer.ts
  core/core.ts
  core/llm/llms/Test.ts
  core/nextEdit/NextEditProvider.ts
  core/nextEdit/README.md
  core/nextEdit/constants.ts
  core/nextEdit/diff/diff.ts
  core/nextEdit/templating/NextEditPromptEngine.ts
  core/package-lock.json
  core/package.json
  core/protocol/ideWebview.ts
  extensions/vscode/e2e/README.md
  extensions/vscode/e2e/TestUtils.ts
  extensions/vscode/e2e/actions/NextEdit.actions.ts
  extensions/vscode/e2e/selectors/NextEdit.selectors.ts
  extensions/vscode/e2e/tests/Edit.test.ts
  extensions/vscode/e2e/tests/NextEdit.test.ts
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  extensions/vscode/src/activation/NextEditWindowManager.ts
  extensions/vscode/src/autocomplete/completionProvider.ts
  extensions/vscode/src/commands.ts
  extensions/vscode/src/extension/VsCodeExtension.ts
  extensions/vscode/src/extension/VsCodeMessenger.ts
  extensions/vscode/src/util/editLoggingUtils.ts
  gui/package-lock.json
  gui/src/pages/config/ContinueFeaturesMenu.tsx
  gui/src/pages/config/UserSettingsForm.tsx
  package-lock.json
  package.json
  packages/openai-adapters/package-lock.json
  packages/openai-adapters/package.json
Labels: lgtm, size:XXL

#6357 YAML config load minP, frequencyPenalty and presencePenalty
  packages/config-yaml/src/schemas/models.ts
Labels: lgtm, size:XS
