Repository continuedev/continue, pull requests merged in 2025-05, with the labels that each got.

#5550 docs: fix minor reference.md typo
  docs/docs/reference.md
Labels: lgtm

#5565 Fix frontmatter in mcp.md
  docs/docs/blocks/mcp.md
Labels: lgtm, size:XS

#5522 watsonx - messages API integration
  core/llm/autodetect.ts
  core/llm/llms/WatsonX.ts
  core/llm/toolSupport.ts
Labels: lgtm

#5592 fix: e2e tests
  .github/workflows/pr_checks.yaml
  extensions/vscode/e2e/README.md
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
Labels: lgtm, size:M

#5548 improv: prevent logger from crashing when logs do not initially exist
  binary/prompt-logs.js
Labels: lgtm

#5579 fix: wait for permissions before initializing messenger
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessenger.kt
Labels: lgtm, size:S

#5582 feat: manual ripgrep downloads for JB
  binary/build.js
  binary/package-lock.json
  binary/package.json
  binary/utils/ripgrep.js
  binary/utils/targets.js
  extensions/intellij/build.gradle.kts
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/PluginConstants.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessengerManager.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/utils/Paths.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/utils/Utils.kt
  extensions/vscode/package-lock.json
  scripts/install-dependencies.ps1
Labels: lgtm, size:XL

#5595 Update default local models
  core/config/onboarding.ts
Labels: lgtm, size:XS

#5559 feat: add keyboard shortcut to autocomplete quickpick
  extensions/vscode/src/commands.ts
Labels: lgtm, size:S

#5596 fix: ollama tool use
  core/llm/llms/Ollama.ts
Labels: lgtm, size:S

#5599 Revert "Update default local models"
  core/config/onboarding.ts
Labels: lgtm, size:XS

#5600 feat(JB): limit to 4 threads in `handleMessage`
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
Labels: lgtm, size:S

#5598 Update Qwen3 tool support
  core/llm/llms/Ollama.ts
  core/llm/toolSupport.ts
Labels: lgtm, size:M

#5601 chore: bump JB version
  extensions/intellij/gradle.properties
Labels: lgtm, size:XS

#5602 bump package.json version
  extensions/vscode/package.json
Labels: size:XS

#5607 chore: :technologist: add vscode github actions extension to recommended list
  .vscode/extensions.json
Labels: lgtm, size:XS

#5503 open config when clicking on editing the prompt
  gui/src/components/mainInput/Lump/sections/PromptsSection.tsx
Labels: lgtm

#5631 fix: use `cmd` for windows MCP connections
  core/context/mcp/MCPConnection.test.ts
  core/context/mcp/MCPConnection.ts
Labels: lgtm, size:M

#4509 Enhancements and fixes to autocomplete behaviour
  core/autocomplete/filtering/streamTransforms/StreamTransformPipeline.ts
  core/autocomplete/util/AutocompleteDebouncer.ts
  core/config/sharedConfig.ts
  core/index.d.ts
  core/util/parameters.ts
  gui/src/components/gui/NumberInput.tsx
  gui/src/pages/config/UserSettingsForm.tsx
Labels: lgtm

#4765 config-yaml: add embedding prefixes support
  packages/config-yaml/src/schemas/models.ts
Labels: lgtm, size:S

#5371 feat(config-yaml): Add promptCaching to Default Completion Options and enable Bedrock Tools Caching
  core/index.d.ts
  core/llm/llms/Bedrock.ts
  packages/config-yaml/src/schemas/models.ts
Labels: lgtm, size:M

#5591 error message when mcp arg has unsubstituted variable
  core/config/yaml/loadYaml.ts
Labels: lgtm, size:S

#5611 Nate/contributin-md
  .github/pull_request_template.md
  CONTRIBUTING.md
  extensions/vscode/CONTRIBUTING.md
Labels: lgtm, size:M

#5639 feat: update tutorial files w/ agent mode step
  extensions/intellij/src/main/resources/continue_tutorial.java
  extensions/intellij/src/main/resources/continue_tutorial.py
  extensions/intellij/src/main/resources/continue_tutorial.ts
  extensions/vscode/continue_tutorial.py
Labels: lgtm, size:L

#5648 fix: use proper alternating colors in KeyboardShortcuts.tsx
  gui/src/pages/config/KeyboardShortcuts.tsx
  gui/tailwind.config.cjs
Labels: lgtm, size:XS

#5652 fix: use bolt icon for shortcuts page
  gui/src/pages/config/UserSettingsForm.tsx
  gui/src/pages/config/index.tsx
Labels: lgtm, size:L

#5538 replace vsce with @vscode/vsce
  .github/workflows/main.yaml
  .github/workflows/preview.yaml
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  extensions/vscode/scripts/package.js
Labels: lgtm, size:XS

#5588 fix test dirs being created inside core folder
  core/test/testDir.ts
Labels: lgtm, size:XS

#5640 Fix apply state actions generating state
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/ApplyActions.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/GeneratingCodeLoader.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/index.tsx
  gui/src/components/StyledMarkdownPreview/index.tsx
  gui/src/pages/gui/ToolCallDiv/FunctionSpecificToolCallDiv.tsx
Labels: lgtm, size:L

#5624 fix: :bug: fixing issues with creating markdown files
  core/autocomplete/filtering/streamTransforms/lineStream.test.ts
  core/autocomplete/filtering/streamTransforms/lineStream.ts
  gui/src/components/StyledMarkdownPreview/utils/headerIsMarkdown.test.ts
  gui/src/components/StyledMarkdownPreview/utils/headerIsMarkdown.ts
  gui/src/components/StyledMarkdownPreview/utils/patchNestedMarkdown.test.ts
  gui/src/components/StyledMarkdownPreview/utils/patchNestedMarkdown.ts
Labels: lgtm, size:L

#5603 jetbrains test configurations
  .idea/runConfigurations/config_yaml_tests.xml
  .idea/runConfigurations/core_tests.xml
  .idea/runConfigurations/openai_adapters_configuration.xml
  .idea/vcs.xml
Labels: lgtm, size:M

#5604 docs: clarify local .env secret pull process for local assistants
  docs/docs/reference.md
Labels: lgtm, size:XS

#5618 fix loading configs from project .continue folder in JetBrains IDEs on Windows (bug #5474)
  packages/config-yaml/src/registryClient.test.ts
  packages/config-yaml/src/registryClient.ts
Labels: lgtm, size:S

#5655 CLA
  .github/workflows/cla.yaml
  CONTRIBUTING.md
  docs/docs/CLA.md
Labels: lgtm, size:L

#5654 Fix selected profile not being persisted
  core/config/ConfigHandler.ts
Labels: lgtm, size:XS

#5656 Fix: codeblocks hanging on one line for tool calls
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/index.tsx
  gui/src/pages/gui/ToolCallDiv/CreateFile.tsx
  gui/src/pages/gui/ToolCallDiv/EditFile.tsx
Labels: lgtm, size:S

#5674 fix: number of completions to generate is not supported
  docs/docs/reference.md
Labels: lgtm, size:XS

#5668 chore: :rotating_light: fix lint errors in gui and introduce gui lint in CI
  .github/workflows/pr_checks.yaml
  gui/.eslintrc.json
  gui/package.json
Labels: lgtm, size:XS

#5678 ci: :green_heart: don't run cla assistant on fork repositories
  .github/workflows/cla.yaml
Labels: lgtm, size:S

#5676 chore: :bookmark: bump intellij version
  .github/workflows/jetbrains-release.yaml
  extensions/intellij/gradle.properties
Labels: lgtm, size:XS

#5682 chore: ignore whitespaces in CLA check
  .github/workflows/cla.yaml
Labels: lgtm, size:XS

#5677 feat: display rules used
  core/index.d.ts
  core/llm/llm.test.ts
  core/llm/rules/getSystemMessageWithRules.ts
  extensions/vscode/e2e/selectors/GUI.selectors.ts
  extensions/vscode/e2e/tests/GUI.test.ts
  gui/src/components/ToggleDiv.tsx
  gui/src/components/mainInput/ContinueInputBox.tsx
  gui/src/components/mainInput/belowMainInput/RulesPeek.tsx
  gui/src/pages/gui/Chat.tsx
  gui/src/pages/gui/ToolCallDiv/SimpleToolCallUI.tsx
  gui/src/redux/slices/sessionSlice.ts
  gui/src/redux/thunks/streamResponse.ts
Labels: lgtm, size:L

#5691 chore: bump
  extensions/vscode/package.json
Labels: lgtm, size:XS

#5587 fix minor problems during intellij ce extension run scripts
  .gitignore
  binary/package-lock.json
  binary/package.json
  extensions/intellij/.run/Start Core Dev Server (CE).run.xml
Labels: lgtm, size:XS

#5653 Update IdeProtocolClient.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
Labels: lgtm, size:S

#5608 :sparkles: add seed coder fim template
  core/autocomplete/templating/AutocompleteTemplate.ts
Labels: lgtm, size:S

#5649 Update troubleshooting.mdx
  docs/docs/troubleshooting.mdx
Labels: lgtm, size:XS

#5636 fix: dont toggle models when toggling assistants
  gui/src/components/modelSelection/ModelSelect.tsx
Labels: lgtm, size:S

#5695 Fix docs
  docs/docs/CLA.md
Labels: size:XS

#5650 feat: add link to Hub on Help Center
  gui/src/pages/config/HelpCenterSection.tsx
Labels: lgtm, size:XS

#5584 tests for uriToFile
  extensions/intellij/build.gradle.kts
  extensions/intellij/gradle.properties
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/Diffs.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/GitService.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/UriUtils.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/ContinuePluginService.kt
  extensions/intellij/src/test/kotlin/com/github/continuedev/continueintellijextension/unit/UriUtilsTest.kt
Labels: lgtm, size:L

#5638 fix: prevent autoscrolling on new tool msgs
  gui/src/pages/gui/Chat.tsx
  gui/src/pages/gui/useAutoScroll.ts
  gui/src/redux/slices/sessionSlice.ts
Labels: lgtm, size:S

#5637 fix: hardcode `fontSize` for tool call status msg
  .idea/jsLinters/eslint.xml
  .idea/prettier.xml
  gui/src/context/LocalStorage.tsx
  gui/src/pages/gui/ToolCallDiv/ToolCallStatusMessage.tsx
Labels: lgtm, size:S

#5680 chore(JB): cleanup `applyToFile` logic
  .continue/rules/intellij-plugin-test-execution.yaml
  core/index.d.ts
  core/protocol/ideWebview.ts
  extensions/intellij/CONTRIBUTING.md
  extensions/intellij/build.gradle.kts
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/ApplyToFileHandler.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/DiffStreamHandler.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/EditorUtils.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/InlineEditAction.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/VerticalDiffBlock.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/types.kt
  extensions/intellij/src/test/kotlin/com/github/continuedev/continueintellijextension/unit/ApplyToFileHandlerTest.kt
  extensions/intellij/src/test/kotlin/com/github/continuedev/continueintellijextension/utils/BrowserUtils.kt
  extensions/vscode/src/diff/vertical/handler.ts
  gui/src/components/AcceptRejectAllButtons.tsx
  gui/src/components/mainInput/CodeToEditCard.tsx
  gui/src/redux/slices/editModeState.ts
  gui/src/redux/thunks/editMode.ts
Labels: lgtm, size:XXL

#5673 Fix: non-existent tool logic, better tool errors
  core/tools/callTool.ts
  gui/src/components/modelSelection/ModeSelect.tsx
Labels: lgtm, size:M

#5708 fix[JB]: misc apply bugs
  .continue/rules/intellij-test-standards.yaml
  binary/build.js
  core/index.d.ts
  core/llm/templates/edit/gpt.ts
  core/protocol/core.ts
  core/protocol/ideWebview.ts
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/ApplyToFileHandler.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/DiffStreamHandler.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/EditorUtils.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/RangeInFileWithContents.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/VerticalDiffBlock.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/types.kt
  extensions/intellij/src/test/kotlin/com/github/continuedev/continueintellijextension/unit/ApplyToFileHandlerTest.kt
  extensions/vscode/package-lock.json
  gui/src/components/AcceptRejectDiffButtons.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/ApplyActions.tsx
  gui/src/components/mainInput/EditModeDetails.tsx
  gui/src/pages/gui/Chat.tsx
  manual-testing-sandbox/test.kt
Labels: lgtm, size:XL

#5659 Nate/log-inline-edit
  extensions/vscode/src/extension/VsCodeMessenger.ts
  packages/config-yaml/src/schemas/data/editInteraction/index.ts
  packages/config-yaml/src/schemas/data/index.ts
Labels: lgtm, size:S

#5657 Setting for auto-accepting agent mode edits
  core/config/migrateSharedConfig.ts
  core/config/sharedConfig.ts
  core/index.d.ts
  docs/docs/customize/deep-dives/settings.md
  docs/static/img/header-buttons.png
  docs/static/img/settings-header.png
  gui/src/components/gui/NumberInput.tsx
  gui/src/components/gui/Switch.tsx
  gui/src/pages/config/UserSettingsForm.tsx
  gui/src/util/clientTools/editImpl.ts
Labels: lgtm, size:L

#5580 handle `data:[DONE]` without space properly
  core/llm/stream.test.ts
  core/llm/stream.ts
  packages/fetch/src/stream.ts
Labels: lgtm, size:M

#5715 make continuedev/fetch package automatically respect HTTP(S)_PROXY, NO_PROXY environment variables
  packages/fetch/jest.config.d.ts
  packages/fetch/jest.config.js
  packages/fetch/jest.config.mjs
  packages/fetch/jest.config.ts
  packages/fetch/package-lock.json
  packages/fetch/package.json
  packages/fetch/src/fetch.test.ts
  packages/fetch/src/fetch.ts
  packages/fetch/src/getAgentOptions.ts
  packages/fetch/src/stream.test.ts
  packages/fetch/src/stream.ts
  packages/fetch/src/util.test.ts
  packages/fetch/src/util.ts
  packages/fetch/tsconfig.json
Labels: lgtm, size:XL

#5702 feat: only autoscroll Continue console when focused on last element
  gui/src/components/console/Details.tsx
Labels: lgtm, size:M

#5732 fix: add Delphi/Pascal syntax highlighting support
  gui/src/components/StyledMarkdownPreview/rehypeHighlightPlugin.ts
Labels: lgtm, size:XS

#5692 chore: :technologist: update the commit message for cla signing
  .github/workflows/cla.yaml
Labels: lgtm, size:XS

#5495 test: :white_check_mark: retry on failed llm api tests
  core/llm/llm.test.ts
Labels: lgtm, size:M

#5739 improv: cancel autocomplete requests after timeout is reached
  core/autocomplete/generation/CompletionStreamer.ts
  core/autocomplete/generation/utils.test.ts
  core/autocomplete/generation/utils.ts
Labels: lgtm, size:L

#5681 chore: specify edit capabilities in `createRuleBlock`
  core/tools/definitions/createRuleBlock.ts
Labels: lgtm, size:XS

#5723 Client URL
  core/config/ConfigHandler.ts
  core/control-plane/AuthTypes.ts
  core/control-plane/auth/index.ts
  core/control-plane/client.ts
  core/control-plane/env.ts
  core/protocol/core.ts
  core/protocol/ide.ts
  core/protocol/webview.ts
  extensions/vscode/src/stubs/WorkOsAuthProvider.ts
  gui/src/context/Auth.tsx
  gui/src/context/MockIdeMessenger.ts
  gui/src/pages/config/AccountButton.tsx
Labels: lgtm, size:L

#5725 read from plist and linux /etc/ files for custom environment
  .gitignore
  core/control-plane/env.ts
  core/control-plane/mdm.test.ts
  core/control-plane/mdm.ts
  core/package-lock.json
  core/package.json
Labels: size:L

#5737 win reg
  core/control-plane/mdm.ts
Labels: lgtm, size:M

#5742 bump
  extensions/vscode/package.json
Labels: size:XS

#5757 await isSignedIn()
  core/config/yaml/loadYaml.ts
  core/control-plane/client.ts
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  gui/package-lock.json
Labels: lgtm, size:S

#5711 style: update button styles and background color
  gui/src/components/index.ts
  gui/src/components/mainInput/Lump/sections/ExploreBlocksButton.tsx
Labels: lgtm, size:XS

#5760 feat: markdown rules
  core/config/ConfigHandler.ts
  core/config/loadLocalAssistants.ts
  core/config/markdown/loadMarkdownRules.ts
  core/config/markdown/parseMarkdownRule.test.ts
  core/config/markdown/parseMarkdownRule.ts
  core/config/profile/doLoadConfig.ts
  core/config/yaml/loadYaml.ts
  core/tools/implementations/createRuleBlock.ts
  extensions/vscode/package.json
Labels: lgtm, size:L

#5748 Fix config merging
  core/config/load.ts
Labels: lgtm, size:S

#5729 feat: add regex to allow for openai o-series models and rename method…
  core/llm/llms/OpenAI.test.ts
  core/llm/llms/OpenAI.ts
Labels: lgtm, size:M

#5517 feat: add support for SSE MCP servers
  core/config/workspace/workspaceBlocks.ts
  core/config/yaml/loadYaml.test.ts
  core/config/yaml/loadYaml.ts
  docs/docs/customize/deep-dives/mcp.mdx
  docs/docs/reference.md
  packages/config-yaml/src/converter.ts
  packages/config-yaml/src/schemas/index.ts
Labels: lgtm, size:L

#5744 Fix: improve command extraction in RunInTerminalButton (#5724)
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/RunInTerminalButton.tsx
  gui/src/components/StyledMarkdownPreview/utils/commandExtractor.test.ts
  gui/src/components/StyledMarkdownPreview/utils/commandExtractor.ts
Labels: lgtm, size:L

#5765 feat(JB): impl `showFile`
  core/index.d.ts
  core/protocol/ideWebview.ts
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/protocol/ideWebview.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/types.kt
Labels: lgtm, size:M

#5777 fix: broken link
  extensions/vscode/package.json
Labels: lgtm, size:XS

#5780 Revert "feat: add support for SSE MCP servers"
  core/config/workspace/workspaceBlocks.ts
  core/config/yaml/loadYaml.test.ts
  core/config/yaml/loadYaml.ts
  docs/docs/customize/deep-dives/mcp.mdx
  docs/docs/reference.md
  packages/config-yaml/src/converter.ts
  packages/config-yaml/src/schemas/index.ts
Labels: lgtm, size:L

#5779 Add Devstral as model supporting tools
  core/llm/toolSupport.test.ts
  core/llm/toolSupport.ts
Labels: lgtm, size:XS

#5781 Match all context to rules
  core/edit/streamDiffLines.ts
  core/llm/constructMessages.ts
  core/llm/rules/getSystemMessageWithRules.test.ts
  core/llm/rules/getSystemMessageWithRules.ts
  core/llm/utils/extractPathsFromCodeBlocks.test.ts
  core/llm/utils/extractPathsFromCodeBlocks.ts
  gui/src/redux/thunks/streamResponse.ts
Labels: lgtm, size:L

#5794 Update troubleshooting.mdx
  docs/docs/troubleshooting.mdx
Labels: lgtm, size:XS

#5766 Full Theme Colors Framework
  core/protocol/ideWebview.ts
  core/protocol/webview.ts
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/GetTheme.kt
  extensions/vscode/package-lock.json
  gui/src/App.tsx
  gui/src/components/StyledMarkdownPreview/SymbolLink.tsx
  gui/src/components/TabBar/TabBar.tsx
  gui/src/components/dialogs/index.tsx
  gui/src/components/find/FindWidget.tsx
  gui/src/components/gui/Alert.tsx
  gui/src/components/index.ts
  gui/src/components/mainInput/TipTapEditor/components/ExpandableToolbarPreview.tsx
  gui/src/context/VscTheme.tsx
  gui/src/hooks/ParallelListeners.tsx
  gui/src/pages/config/HelpCenterSection.tsx
  gui/src/pages/config/KeyboardShortcuts.tsx
  gui/src/styles/ThemePage.tsx
  gui/src/styles/theme.test.ts
  gui/src/styles/theme.ts
  gui/src/styles/utils.ts
  gui/src/util/navigation.ts
  gui/tailwind.config.cjs
Labels: lgtm, size:XXL

#5796 docs: specify the schema versions in dev data reference
  docs/docs/reference.md
Labels: lgtm, size:XS

#5800 feat: :sparkles: Add support for Claude Sonnet 4
  core/llm/llms/Bedrock.ts
  core/llm/toolSupport.ts
Labels: lgtm, size:XS

#5807 Nate/watsonx-rules-support
  core/llm/llms/stubs/ContinueProxy.ts
  core/package-lock.json
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  gui/package-lock.json
  packages/config-yaml/package-lock.json
  packages/config-yaml/package.json
  packages/config-yaml/src/load/clientRender.ts
  packages/openai-adapters/README.md
  packages/openai-adapters/package.json
  packages/openai-adapters/src/apis/WatsonX.ts
  packages/openai-adapters/src/index.ts
  packages/openai-adapters/src/test/main.test.ts
  packages/openai-adapters/src/types.ts
Labels: size:L

#5811 Nate/sse
  core/config/yaml/loadYaml.ts
  extensions/vscode/package-lock.json
  packages/config-yaml/src/schemas/index.ts
Labels: size:S

#5823 feat: improve StreamError dialog
  gui/src/pages/gui/StreamError.tsx
Labels: lgtm, size:L

#5741 Fix find widget alignment
  gui/src/components/TabBar/TabBar.tsx
  gui/src/components/find/FindWidget.tsx
  gui/src/components/find/findWidgetSearch.ts
  gui/src/components/find/useDebounce.ts
  gui/src/components/find/useElementSize.ts
  gui/src/pages/gui/Chat.tsx
Labels: lgtm, size:XL

#5799 feat: `description` in markdown yaml
  core/config/markdown/parseMarkdownRule.test.ts
  core/config/markdown/parseMarkdownRule.ts
  core/tools/definitions/createRuleBlock.ts
  core/tools/implementations/createRuleBlock.test.ts
  core/tools/implementations/createRuleBlock.ts
  packages/config-yaml/src/schemas/index.ts
Labels: lgtm, size:L

#5810 reo fix
  docs/docusaurus.config.js
  docs/static/scripts/custom-reo.js
Labels: lgtm, size:XS

#5675 Feat: support maxStopWords model config option in yaml
  core/config/util.ts
  core/control-plane/schema.ts
  docs/docs/reference.md
  packages/config-yaml/src/schemas/models.ts
Labels: lgtm, size:XS

#5694 Make Apply Streaming Cancelable
  core/commands/slash/http.ts
  core/core.ts
  core/edit/recursiveStream.ts
  core/edit/streamDiffLines.ts
  core/index.d.ts
  core/llm/index.ts
  core/llm/llms/Anthropic.ts
  core/llm/llms/Asksage.ts
  core/llm/llms/Cloudflare.ts
  core/llm/llms/Cohere.ts
  core/llm/llms/Deepseek.ts
  core/llm/llms/Flowise.ts
  core/llm/llms/FreeTrial.ts
  core/llm/llms/Gemini.ts
  core/llm/llms/HuggingFaceInferenceAPI.ts
  core/llm/llms/HuggingFaceTGI.ts
  core/llm/llms/Inception.ts
  core/llm/llms/LlamaCpp.ts
  core/llm/llms/Moonshot.ts
  core/llm/llms/Ollama.ts
  core/llm/llms/OpenAI.ts
  core/llm/llms/SiliconFlow.ts
  core/llm/llms/VertexAI.ts
  core/llm/llms/WatsonX.ts
  core/llm/stream.test.ts
  core/llm/stream.ts
  core/llm/streamChat.ts
  core/package-lock.json
  core/package.json
  core/protocol/core.ts
  core/util/abortManager.ts
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/Diffs.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/DiffStreamHandler.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/types.kt
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  extensions/vscode/src/commands.ts
  extensions/vscode/src/diff/vertical/manager.ts
  extensions/vscode/src/extension/VsCodeExtension.ts
  gui/package-lock.json
  gui/src/components/mainInput/Lump/LumpToolbar.tsx
  gui/src/pages/gui/Chat.tsx
  manual-testing-sandbox/AdvancedPage.tsx
  packages/fetch/.gitignore
  packages/fetch/jest.globals.d.ts
  packages/fetch/package-lock.json
  packages/fetch/package.json
  packages/fetch/src/stream.test.ts
  packages/fetch/src/stream.ts
  packages/fetch/tsconfig.json
  packages/openai-adapters/package-lock.json
  packages/openai-adapters/package.json
  packages/openai-adapters/src/apis/Anthropic.ts
  packages/openai-adapters/src/apis/Cohere.ts
  packages/openai-adapters/src/apis/Relace.ts
  packages/openai-adapters/src/util/emptyChatCompletion.ts
Labels: lgtm, size:XL

#5834 show stderr in the error message for failed MCP servers
  core/context/mcp/MCPConnection.test.ts
  core/context/mcp/MCPConnection.ts
  core/package-lock.json
  core/package.json
Labels: lgtm, size:M

#5833 Nate/vllm-no-fim
  core/llm/llms/Vllm.ts
  core/llm/llms/stubs/ContinueProxy.ts
  core/llm/llms/test/supportsFim.test.ts
  core/llm/toolSupport.ts
  extensions/vscode/package.json
Labels: lgtm, size:M

#5802 Theme colors rule and contributing guide section
  .continue/rules/colors.yaml
  CONTRIBUTING.md
Labels: lgtm, size:L

#5829 Mcp streamable http
  binary/package-lock.json
  core/context/mcp/MCPConnection.ts
  core/index.d.ts
  core/package-lock.json
  extensions/vscode/config_schema.json
  gui/package-lock.json
Labels: lgtm, size:M

#5865 fix: :bug: Fix the generating animation
  gui/src/components/index.ts
Labels: lgtm, size:XS

#5849 Fix tool call delta name streaming logic
  gui/src/redux/slices/sessionSlice.ts
  gui/src/util/toolCallState.test.ts
  gui/src/util/toolCallState.ts
Labels: lgtm, size:L

#5837 Add alwaysApply property to rules for better control over rule applic…
  core/config/markdown/parseMarkdownRule.test.ts
  core/config/markdown/parseMarkdownRule.ts
  core/index.d.ts
  core/llm/rules/getSystemMessageWithRules.test.ts
  core/llm/rules/getSystemMessageWithRules.ts
  core/tools/definitions/createRuleBlock.ts
  core/tools/implementations/createRuleBlock.test.ts
  core/tools/implementations/createRuleBlock.ts
  docs/docs/customize/deep-dives/rules.md
  gui/src/components/mainInput/belowMainInput/RulesPeek.tsx
  packages/config-yaml/src/schemas/index.ts
Labels: lgtm, size:XL

#5670 feat: add current file context automatically to chat
  .vscode/settings.json
  core/config/sharedConfig.ts
  core/index.d.ts
  extensions/vscode/src/VsCodeIde.ts
  gui/src/components/mainInput/TipTapEditor/useMainEditorWebviewListeners.ts
  gui/src/components/mainInput/TipTapEditor/utils/insertCurrentFileContextMention.ts
  gui/src/pages/config/UserSettingsForm.tsx
Labels: lgtm, size:M

#5846 docs: specify that mcp can be used in agent mode only
  docs/docs/customize/deep-dives/mcp.mdx
Labels: lgtm, size:XS

#5879 Disable diff autocomplete snippets in jetbrains
  core/autocomplete/snippets/getAllSnippets.ts
  core/autocomplete/util/HelperVars.ts
Labels: lgtm, size:M

#5887 Fix tool call args UI overflow
  gui/src/pages/gui/Chat.tsx
  gui/src/pages/gui/ToolCallDiv/SimpleToolCallUI.tsx
  gui/src/pages/gui/ToolCallDiv/ToolCall.tsx
  gui/src/pages/gui/ToolCallDiv/ToolCallArgs.tsx
  gui/src/pages/gui/ToolCallDiv/ToolCallStatusMessage.tsx
  gui/src/pages/gui/ToolCallDiv/index.tsx
Labels: lgtm, size:L

#5888 Improve selected jetbrains theme colors
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/GetTheme.kt
  gui/src/components/ModeSelect/ModeSelect.tsx
  gui/src/components/ui/Listbox.tsx
Labels: lgtm, size:S

#5895 Bump jetbrains to 1.0.21
  extensions/intellij/gradle.properties
Labels: lgtm, size:XS

#5892 Fix Cmd J not working in Jetbrains
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/types.kt
Labels: lgtm, size:S

#5867 feat: `requestRule` tool
  core/config/load.ts
  core/config/profile/doLoadConfig.ts
  core/config/yaml/loadYaml.ts
  core/core.ts
  core/index.d.ts
  core/tools/builtIn.ts
  core/tools/callTool.ts
  core/tools/definitions/requestRule.test.ts
  core/tools/definitions/requestRule.ts
  core/tools/implementations/requestRule.ts
  core/tools/index.ts
  gui/src/redux/slices/uiSlice.ts
  gui/src/redux/thunks/callCurrentTool.ts
Labels: lgtm, size:L

#5908 added a rule to make the model answer specifically about continue
  .continue/rules/continue-specificity.md
Labels: lgtm, size:XS

#5919 Jacob/feature/call-alongside-autocomplete
  core/nextEdit/NextEditProvider.ts
  extensions/vscode/src/autocomplete/completionProvider.ts
Labels: size:L

#5920 Jacob/feature/call alongside autocomplete
  core/nextEdit/IgnoreNextEdit.ts
  extensions/vscode/src/autocomplete/completionProvider.ts
Labels: size:M

#5923 Revision on #5921 per PR review
  core/nextEdit/IgnoreNextEdit.ts
  core/nextEdit/constants.ts
  extensions/vscode/src/autocomplete/completionProvider.ts
Labels: size:XS

#5560 prevent markdown table from breaking on formatted nodes
  gui/src/components/StyledMarkdownPreview/utils/remarkTables.tsx
Labels: lgtm, size:M

#5726 fix: reverted the URL of llama.cpp back to 'completion'.
  core/llm/llms/LlamaCpp.ts
Labels: lgtm, size:XS

#5921 Feature/nextEdit
  core/nextEdit/NextEditProvider.ts
  core/nextEdit/constants.ts
  extensions/vscode/src/autocomplete/completionProvider.ts
Labels: lgtm, size:L
