Repository continuedev/continue, pull requests merged in 2025-10, with the labels that each got.

#8047 fix: adds working snyk workflow
  docs/guides/snyk-mcp-continue-cookbook.mdx
Labels: lgtm, size:L

#8007 feat: status tool for cn
  extensions/cli/src/commands/ls.ts
  extensions/cli/src/commands/remote.test.ts
  extensions/cli/src/commands/remote.ts
  extensions/cli/src/tools/index.tsx
  extensions/cli/src/tools/status.ts
  extensions/cli/src/util/apiClient.test.ts
  extensions/cli/src/util/apiClient.ts
Labels: lgtm, size:XL

#7692 refresh workspace dirs when folders are added
  core/core.ts
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt
  extensions/vscode/src/extension/VsCodeExtension.ts
  extensions/vscode/src/util/ideUtils.ts
Labels: lgtm, size:M

#7467 feat: added UI for global rule creation
  core/config/markdown/loadMarkdownRules.ts
  core/config/workspace/workspaceBlocks.ts
  core/core.ts
  core/protocol/core.ts
  core/protocol/passThrough.ts
  extensions/vscode/src/extension/VsCodeExtension.ts
  gui/src/components/DropdownButton.tsx
  gui/src/pages/config/sections/RulesSection.tsx
Labels: lgtm, size:XS

#8056 fix: filter out markdown delimiters from next edit responses
  core/autocomplete/postprocessing/index.test.ts
  core/autocomplete/postprocessing/index.ts
  core/config/types.ts
  core/core.ts
  core/index.d.ts
  core/llm/index.ts
  core/nextEdit/NextEditLoggingService.ts
  core/nextEdit/providers/BaseNextEditProvider.ts
  core/nextEdit/types.ts
  extensions/vscode/package.json
  extensions/vscode/src/activation/JumpManager.ts
  extensions/vscode/src/activation/NextEditWindowManager.ts
  extensions/vscode/src/activation/SelectionChangeManager.ts
  extensions/vscode/src/autocomplete/completionProvider.ts
  extensions/vscode/src/extension/VsCodeExtension.ts
  packages/config-yaml/src/schemas/data/nextEditOutcome/index.ts
  packages/config-yaml/src/schemas/data/nextEditOutcome/v0.2.0.ts
Labels: size:L

#8082 docs: add Continue Docs MCP cookbook and update navigation
  docs/docs.json
  docs/guides/continue-docs-mcp-cookbook.mdx
  docs/guides/overview.mdx
Labels: lgtm, size:XL

#8079 docs: Add Sanity MCP Continue cookbook with proper agent configs for CI/interactive modes
  docs/guides/sanity-mcp-continue-cookbook.mdx
Labels: lgtm, size:XL

#8076 feat: add weekly cn task to check documentation
  .github/workflows/run-continue-agent.yml
  .github/workflows/tidy-up-codebase.yml
  core/indexing/README.md
  extensions/cli/spec/shell-mode.md
Labels: lgtm, size:L

#8100 feat: add OpenRouter API with Anthropic prompt caching support
  packages/openai-adapters/src/apis/OpenRouter.test.ts
  packages/openai-adapters/src/apis/OpenRouter.ts
  packages/openai-adapters/src/apis/OpenRouterCaching.ts
  packages/openai-adapters/src/index.ts
Labels: size:XL

#8073 Detect invokable rules located in 'prompts' directory
  core/config/markdown/loadMarkdownRules.ts
  core/promptFiles/getPromptFiles.ts
  core/promptFiles/index.ts
Labels: lgtm, size:M

#7709 fix: use common process.env values to launch MCP
  core/context/mcp/MCPConnection.ts
Labels: lgtm, size:S

#8088 docs: Add Chrome DevTools Performance Cookbook with MCP integration
  docs/docs.json
  docs/guides/chrome-devtools-mcp-performance.mdx
  docs/guides/netlify-mcp-continuous-deployment.mdx
  docs/guides/overview.mdx
  docs/guides/posthog-github-continuous-ai.mdx
  docs/guides/snyk-mcp-continue-cookbook.mdx
Labels: lgtm, size:XL

#7505 feat: Adjusted MCPConnection logic so the cwd is resolved to current workspace folder.
  core/context/mcp/MCPConnection.ts
  core/context/mcp/MCPConnection.vitest.ts
Labels: lgtm, size:M

#8111 fix: separate preprocessed tool args
  core/index.d.ts
  gui/src/pages/gui/ToolCallDiv/FunctionSpecificToolCallDiv.tsx
  gui/src/redux/slices/sessionSlice.ts
  gui/src/redux/thunks/enhanceParsedArgs.ts
  gui/src/redux/thunks/preprocessToolCallArgs.ts
  gui/src/util/clientTools/editImpl.ts
Labels: lgtm, size:M

#8112 fix: add max depth to file indexing
  extensions/cli/src/services/FileIndexService.ts
Labels: lgtm, size:XS

#8130 Revise build steps in BUILD.md
  extensions/cli/BUILD.md
Labels: size:XS

#8133 Fix wrong document about Force Legacy Completions Endpoint
  docs/customize/model-providers/top-level/openai.mdx
Labels: size:XS

#8143 feat(cli): mcp oauth using mcp-remote
  extensions/cli/src/services/MCPService.ts
Labels: size:M
