Repository continuedev/continue, pull requests merged in 2025-09, with the labels that each got.

#7503 feat: paste images in cn
  extensions/cli/package-lock.json
  extensions/cli/package.json
  extensions/cli/src/ui/ImagePaste.test.ts
  extensions/cli/src/ui/TextBuffer.ts
  extensions/cli/src/ui/UserInput.tsx
  extensions/cli/src/ui/__tests__/TUIChat.interruption.minimal.test.tsx
  extensions/cli/src/ui/components/MemoizedMessage.formatDisplay.test.tsx
  extensions/cli/src/ui/components/MemoizedMessage.tsx
  extensions/cli/src/ui/components/ScreenContent.tsx
  extensions/cli/src/ui/hooks/useChat.compaction.ts
  extensions/cli/src/ui/hooks/useChat.helpers.ts
  extensions/cli/src/ui/hooks/useChat.imageProcessing.ts
  extensions/cli/src/ui/hooks/useChat.ts
  extensions/cli/src/ui/hooks/useUserInput.ts
Labels: size:XXL

#7512 refactor: duplicate chat history state
  extensions/cli/CHAT_HISTORY_SERVICE_MIGRATION_PLAN.md
  extensions/cli/package-lock.json
  extensions/cli/package.json
  extensions/cli/src/args.ts
  extensions/cli/src/commands/chat.ts
  extensions/cli/src/commands/commands.ts
  extensions/cli/src/commands/serve.helpers.ts
  extensions/cli/src/commands/serve.ts
  extensions/cli/src/compaction.ts
  extensions/cli/src/flags/flagValidator.ts
  extensions/cli/src/index.ts
  extensions/cli/src/services/ChatHistoryService.test.ts
  extensions/cli/src/services/ChatHistoryService.ts
  extensions/cli/src/services/index.ts
  extensions/cli/src/services/types.ts
  extensions/cli/src/slashCommands.ts
  extensions/cli/src/stream/handleToolCalls.ts
  extensions/cli/src/stream/streamChatResponse.helpers.ts
  extensions/cli/src/stream/streamChatResponse.ts
  extensions/cli/src/test-helpers/ui-test-context.ts
  extensions/cli/src/ui/AppRoot.tsx
  extensions/cli/src/ui/TUIChat.tsx
  extensions/cli/src/ui/__tests__/TUIChat.fileSearch.test.tsx
  extensions/cli/src/ui/__tests__/TUIChat.slashCommands.test.tsx
  extensions/cli/src/ui/components/MemoizedMessage.tsx
  extensions/cli/src/ui/hooks/useChat.helpers.ts
  extensions/cli/src/ui/hooks/useChat.remote.helpers.ts
  extensions/cli/src/ui/hooks/useChat.stream.helpers.ts
  extensions/cli/src/ui/hooks/useChat.ts
  extensions/cli/src/ui/hooks/useChat.types.ts
  extensions/cli/src/ui/hooks/useUserInput.ts
  extensions/cli/src/ui/index.ts
  extensions/cli/src/ui/types.ts
  packages/openai-adapters/package-lock.json
Labels: size:XXL

#7523 fix: Don't fail on non-fatal errors in CLI
  extensions/cli/src/configLoader.ts
Labels: lgtm, size:S

#7521 Revert "fix: recover Continue process after unexpected exceptions (#7463)
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessenger.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessengerManager.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/process/BackoffCalculator.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/process/ContinueBinaryProcess.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/process/ContinueProcessHandler.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/proxy/ProxyPoolingActivity.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/ContinuePluginService.kt
  extensions/intellij/src/test/kotlin/com/github/continuedev/continueintellijextension/unit/BackoffCalculatorTest.kt
Labels: lgtm, size:L

#7445 chore: :white_check_mark: Add ui tests for the new Unified Terminal
  gui/src/components/UnifiedTerminal/UnifiedTerminal.test.tsx
  gui/src/components/UnifiedTerminal/UnifiedTerminal.tsx
Labels: lgtm, size:L

#7468 fix: HOTFIX sanitize mcp names
  core/tools/mcpToolName.ts
  core/tools/mcpToolName.vitest.ts
Labels: lgtm, size:M, hotfix

#7459 feat: add continuous AI Guide
  docs/docs.json
  docs/guides/continuous-ai.mdx
  docs/guides/overview.mdx
Labels: lgtm, size:L

#7527 docs: Update READMEs to use relative rather than absolute paths
  README.md
  extensions/intellij/README.md
  extensions/vscode/README.md
Labels: lgtm, size:S

#7515 feat: show users how to paste image in cli
  extensions/cli/CHAT_HISTORY_SERVICE_MIGRATION_PLAN.md
  extensions/cli/package-lock.json
  extensions/cli/src/ui/TUIChat.tsx
  extensions/cli/src/ui/TextBuffer.ts
  extensions/cli/src/ui/UserInput.tsx
  extensions/cli/src/ui/__tests__/TUIChat.fileSearch.test.tsx
  extensions/cli/src/ui/__tests__/TUIChat.slashCommands.test.tsx
  extensions/cli/src/ui/components/BottomStatusBar.tsx
  extensions/cli/src/ui/components/ScreenContent.tsx
  extensions/cli/src/ui/hooks/useClipboardMonitor.ts
  extensions/cli/src/ui/hooks/useUserInput.ts
  extensions/cli/src/util/clipboard.test.ts
  extensions/cli/src/util/clipboard.ts
  packages/openai-adapters/package-lock.json
Labels: size:XXL

#7265 feat: keep assistant menu open when clicking reload
  gui/src/components/AssistantAndOrgListbox/index.tsx
Labels: lgtm, size:XS

#7480 chore: remove katex font links to avoid warnings
  gui/src/components/StyledMarkdownPreview/katex.css
Labels: lgtm, size:L

#7161 feat: :sparkles: Add experimental range tool for file operations
  core/tools/builtIn.ts
  core/tools/callTool.ts
  core/tools/definitions/index.ts
  core/tools/definitions/readFileRange.ts
  core/tools/implementations/readFileRange.integration.vitest.ts
  core/tools/implementations/readFileRange.ts
  core/tools/implementations/readFileRange.vitest.ts
  core/tools/index.ts
  core/tools/parseArgs.ts
  core/tools/parseArgs.vitest.ts
Labels: size:L

#7531 Display security warnings for potentially dangerous commands
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/index.test.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/index.tsx
Labels: lgtm, size:L

#7234 feat: org policies for indexing and mcp
  core/config/ConfigHandler.ts
  core/config/load.ts
  core/config/profile/doLoadConfig.ts
  core/config/yaml/loadYaml.ts
  core/context/mcp/MCPManagerSingleton.ts
  gui/src/components/mainInput/Lump/sections/mcp/MCPSection.tsx
  gui/src/pages/config/UserSettingsForm.tsx
  packages/config-yaml/src/schemas/policy.ts
Labels: lgtm, size:L

#7378 feat: ctrl+c once to clear input, twice to exit. Refactoring, bug fixes
  extensions/cli/spec/ctrl-c-behavior.md
  extensions/cli/src/__tests__/CtrlCProcessHandling.test.ts
  extensions/cli/src/index.ts
  extensions/cli/src/ui/ConfigSelector.tsx
  extensions/cli/src/ui/FreeTrialTransitionUI.tsx
  extensions/cli/src/ui/MCPSelector.tsx
  extensions/cli/src/ui/Selector.tsx
  extensions/cli/src/ui/ServiceDebugger.tsx
  extensions/cli/src/ui/SessionSelector.tsx
  extensions/cli/src/ui/SlashCommandUI.tsx
  extensions/cli/src/ui/UserInput.tsx
  extensions/cli/src/ui/__tests__/BottomStatusBarCtrlC.test.tsx
  extensions/cli/src/ui/__tests__/CtrlC.test.tsx
  extensions/cli/src/ui/__tests__/CtrlCInputClearing.test.tsx
  extensions/cli/src/ui/__tests__/FreeTrialTransitionUI.test.tsx
  extensions/cli/src/ui/components/BottomStatusBar.tsx
  extensions/cli/src/ui/components/ToolPermissionSelector.tsx
  extensions/cli/src/ui/hooks/useUserInput.ts
  extensions/cli/src/ui/index.ts
  extensions/cli/src/ui/styles.ts
Labels: lgtm, size:XL

#7535 Update telemetryService.ts
  extensions/cli/spec/otlp-metrics.md
  extensions/cli/src/telemetry/telemetryService.ts
Labels: lgtm, size:L

#7254 chore: remove ids from tooltips
  gui/src/components/AcceptRejectDiffButtons.tsx
  gui/src/components/AssistantAndOrgListbox/index.tsx
  gui/src/components/AssistantAndOrgListbox/shared.tsx
  gui/src/components/GenerateRuleDialog/GenerationScreen.tsx
  gui/src/components/InfoHover.tsx
  gui/src/components/ModeSelect/ModeSelect.tsx
  gui/src/components/OnboardingCard/components/OllamaModelDownload.tsx
  gui/src/components/OnboardingCard/components/OnboardingCardLanding.tsx
  gui/src/components/StyledMarkdownPreview/FilenameLink.tsx
  gui/src/components/StyledMarkdownPreview/MermaidBlock.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/ApplyActions.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/CopyButton.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/CreateFileButton.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/FileInfo.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/InsertButton.tsx
  gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/ToolbarButtonWithTooltip.tsx
  gui/src/components/StyledMarkdownPreview/SymbolLink.tsx
  gui/src/components/StyledMarkdownPreview/index.tsx
  gui/src/components/dialogs/AddDocsDialog.tsx
  gui/src/components/gui/HeaderButtonWithToolTip.tsx
  gui/src/components/gui/Tooltip.tsx
  gui/src/components/loaders/FreeTrialProgressBar.tsx
  gui/src/components/mainInput/ContextStatus.tsx
  gui/src/components/mainInput/InputToolbar.tsx
  gui/src/components/mainInput/Lump/LumpToolbar/BlockSettingsTopToolbar.tsx
  gui/src/components/mainInput/Lump/sections/docs/StatusIndicator.tsx
  gui/src/components/mainInput/Lump/sections/mcp/MCPSection.tsx
  gui/src/components/mainInput/Lump/sections/tool-policies/ToolPolicyItem.tsx
  gui/src/pages/config/ModelRoleSelector.tsx
  gui/src/pages/config/UserSettingsForm.tsx
Labels: lgtm, size:XXL

#7587 fix: bump semver check for extension release
  .github/workflows/main.yaml
  CONTRIBUTING.md
Labels: lgtm, size:XS

#7560 fix: don't show unchanged diff sections in extension UI
  gui/src/pages/gui/ToolCallDiv/FindAndReplace.tsx
Labels: lgtm, size:L

#7610 fix: ignore Stream closed exceptions on flush
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/process/ContinueProcessHandler.kt
Labels: lgtm, size:S

#7608 fix: don't use override-only actionPerformed to invoke action
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/error/ContinueErrorSubmitter.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/license/AddLicenseKey.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/license/AddLicenseKeyDialog.kt
Labels: lgtm, size:M

#7598 fix(docs): broken settings page links
  docs/features/autocomplete/how-to-customize.mdx
  docs/reference/deprecated-docs.mdx
Labels: lgtm, size:XS

#7537 feat: CLI shell mode
  extensions/cli/spec/shell-mode.md
  extensions/cli/src/slashCommands.ts
  extensions/cli/src/ui/UserInput.tsx
  extensions/cli/src/ui/hooks/useChat.shellMode.test.ts
  extensions/cli/src/ui/hooks/useChat.shellMode.ts
  extensions/cli/src/ui/hooks/useChat.ts
  extensions/cli/src/ui/hooks/useUserInput.ts
Labels: lgtm, size:XL

#7578 fix: aborterror2 during stream fim
  core/llm/index.ts
Labels: lgtm, size:S

#7593 Handle review comment threads in GitHub workflow
  .github/workflows/respond-to-cubic.yaml
  extensions/cli/src/tools/runTerminalCommand.ts
Labels: lgtm, size:M

#7612 chore: bump package.json
  extensions/vscode/package.json
Labels: lgtm, size:XS

#7597 feat: add tooltips to user settings page
  gui/src/components/gui/Switch.tsx
  gui/src/pages/config/UserSettingsForm.tsx
Labels: lgtm, size:M

#7640 docs: assistant --> agent
  docs/chat/how-to-use-it.mdx
  docs/customization/overview.mdx
  docs/customization/rules.mdx
  docs/customize/deep-dives/configuration.mdx
  docs/customize/deep-dives/mcp.mdx
  docs/customize/deep-dives/rules.mdx
  docs/customize/deep-dives/rules.mdx.backup
  docs/customize/deep-dives/slash-commands.mdx
  docs/customize/model-roles.mdx
  docs/customize/model-roles/00-intro.mdx
  docs/customize/model-roles/intro.mdx
  docs/docs.json
  docs/faqs.mdx
  docs/features/agent/how-to-customize.mdx
  docs/features/edit/how-to-customize.mdx
  docs/getting-started/extensions.mdx
  docs/getting-started/install.mdx
  docs/getting-started/overview.mdx
  docs/getting-started/quick-start.mdx
  docs/guides/continuous-ai.mdx
  docs/guides/ollama-guide.mdx
  docs/guides/understanding-agents.mdx
  docs/hub/agents/create-an-agent.mdx
  docs/hub/agents/edit-an-agent.mdx
  docs/hub/agents/intro.mdx
  docs/hub/agents/use-an-agent.mdx
  docs/hub/assistants/create-an-assistant.mdx
  docs/hub/assistants/edit-an-assistant.mdx
  docs/hub/assistants/intro.mdx
  docs/hub/assistants/use-an-assistant.mdx
  docs/hub/blocks/block-types.mdx
  docs/hub/blocks/create-a-block.mdx
  docs/hub/blocks/intro.mdx
  docs/hub/blocks/use-a-block.mdx
  docs/hub/governance/creating-an-org.mdx
  docs/hub/secrets/secret-types.mdx
  docs/hub/sharing.mdx
  docs/hub/source-control.mdx
  docs/reference.mdx
  docs/reference/continue-mcp.mdx
  packages/continue-sdk/python/api/docs/DefaultApi.md
  packages/continue-sdk/python/api/docs/GetAssistant200Response.md
  packages/continue-sdk/python/api/docs/ListAssistants200ResponseInner.md
  packages/continue-sdk/python/api/docs/ListAssistants200ResponseInnerConfigResult.md
Labels: lgtm, size:L

#7630 feat(scaleway): update supported models
  core/llm/llms/Scaleway.ts
Labels: lgtm, size:XS

#7408 fix: close drag over message overlay during onDrop
  gui/src/components/mainInput/TipTapEditor/TipTapEditor.tsx
Labels: lgtm, size:XS

#7621 feat: CLI: add diagnostics to /info screen
  extensions/cli/src/infoScreen.ts
  extensions/cli/src/slashCommands.test.ts
  extensions/cli/src/slashCommands.ts
Labels: lgtm, size:L

#7643 feat: cli: press enter to continue
  extensions/cli/package-lock.json
  extensions/cli/src/ui/TipsDisplay.tsx
  extensions/cli/src/ui/UserInput.tsx
  extensions/cli/src/ui/__tests__/TUIChat.interruption.minimal.test.tsx
Labels: size:S

#7645 chore: prerelease versions
  extensions/intellij/gradle.properties
  extensions/vscode/package.json
Labels: size:XS

#7591 note whether headless mode / github actions in telemetry
  extensions/cli/src/__mocks__/services/BaseService.ts
  extensions/cli/src/services/BaseService.test.ts
  extensions/cli/src/telemetry/posthogService.errorHandling.test.ts
  extensions/cli/src/telemetry/posthogService.ts
  extensions/cli/src/version.ts
Labels: lgtm, size:L

#6323 feat: run dependent indexer based on context provider
  core/context/providers/CodeContextProvider.ts
  core/context/providers/CodebaseContextProvider.ts
  core/context/providers/FolderContextProvider.ts
  core/core.ts
  core/index.d.ts
  core/indexing/CodebaseIndexer.test.ts
  core/indexing/CodebaseIndexer.ts
  gui/src/context/SubmenuContextProviders.tsx
Labels: lgtm, size:L

#7663 chore: bump prerelease versions
  extensions/intellij/gradle.properties
  extensions/vscode/package.json
Labels: lgtm, size:XS

#7674 HOTFIX revert "fix: diff colors should reach till end"
  gui/src/pages/gui/ToolCallDiv/FindAndReplace.tsx
Labels: lgtm, size:S

#7677 fix: HOTFIX response actions disappearing and causing jumping while streaming
  gui/src/components/StepContainer/StepContainer.tsx
Labels: size:S, hotfix

#7681 feat: add filepath to apply prompt template vars
  core/edit/streamDiffLines.ts
  extensions/vscode/src/apply/ApplyManager.ts
  extensions/vscode/src/diff/vertical/manager.ts
  gui/src/util/clientTools/editImpl.ts
Labels: size:L

#7684 fix: :pencil2: Fix typo in No Parallel Tool Calling Instruction
  core/tools/definitions/editFile.ts
  core/tools/definitions/multiEdit.ts
  core/tools/definitions/singleFindAndReplace.ts
Labels: lgtm, size:S

#7652 fix: :ambulance: Fix bedrock conversation prompt caching
  core/llm/llms/Bedrock.test.ts
  core/llm/llms/Bedrock.ts
Labels: lgtm, size:M

#7592 feat: pass --config to cn remote
  .github/workflows/respond-to-cubic.yaml
  extensions/cli/src/commands/remote.test.ts
  extensions/cli/src/commands/remote.ts
  extensions/cli/src/index.ts
Labels: size:M

#7669 feat: /init slash command for CLI
  extensions/cli/src/commands/commands.ts
  extensions/cli/src/commands/init.ts
  extensions/cli/src/slashCommands.ts
  extensions/cli/src/ui/TipsDisplay.tsx
Labels: size:M

#7691 chore: vs code 1.3.7
  extensions/vscode/package.json
Labels: size:XS

#7665 feat: parse for thinking tags and dim them
  extensions/cli/src/ui/MarkdownRenderer.thinking.test.tsx
  extensions/cli/src/ui/MarkdownRenderer.tsx
Labels: lgtm, size:M

#7728 fix: OTLP reduced cardinality and other OTel improvements
  core/indexing/docs/DocsService.ts
  extensions/cli/src/auth/workos.helpers.ts
  extensions/cli/src/commands/chat.ts
  extensions/cli/src/commands/login.ts
  extensions/cli/src/commands/remote-test.ts
  extensions/cli/src/commands/remote.ts
  extensions/cli/src/commands/serve.test.ts
  extensions/cli/src/commands/serve.ts
  extensions/cli/src/flags/flagValidator.ts
  extensions/cli/src/freeTrialTransition.ts
  extensions/cli/src/index.ts
  extensions/cli/src/stream/streamChatResponse.helpers.ts
  extensions/cli/src/stream/streamChatResponse.ts
  extensions/cli/src/telemetry/headerUtils.ts
  extensions/cli/src/telemetry/telemetryService.ts
  extensions/cli/src/tools/exit.ts
  extensions/cli/src/ui/hooks/useChat.helpers.ts
  extensions/cli/src/ui/hooks/useUserInput.ts
  extensions/cli/src/util/exit.ts
Labels: size:L

#7743 fix: remove duplicate toggleToolGroupSetting call in ToolPoliciesGroup.tsx
  gui/src/pages/config/components/ToolPoliciesGroup.tsx
Labels: lgtm, size:XS

#7718 docs: add ollama alternative to use system message tools
  docs/guides/ollama-guide.mdx
  docs/images/guides/images/agent-not-supported.png
Labels: lgtm, size:XS

#7758 chore: package version bumps: fetch and config-yaml
  packages/config-yaml/package-lock.json
  packages/config-yaml/package.json
  packages/fetch/package-lock.json
  packages/fetch/package.json
Labels: lgtm, size:XS

#7763 fix: missing secret declarations in reusable workflow
  .github/workflows/reusable-release.yml
Labels: lgtm, size:XS

#7748 perf: memoize input box to avoid re-render on each keystroke
  gui/src/components/mainInput/ContinueInputBox.tsx
  gui/src/components/mainInput/InputToolbar.tsx
  gui/src/components/mainInput/TipTapEditor/TipTapEditor.tsx
  gui/src/components/mainInput/TipTapEditor/utils/keyHandlers.ts
  gui/src/hooks/useRenderDebug.tsx
  gui/src/index.css
  gui/src/pages/gui/Chat.tsx
Labels: lgtm, size:L

#7765 fix: mistral and relace open ai adapters tests
  packages/openai-adapters/src/test/main.test.ts
  packages/openai-adapters/src/test/util.ts
Labels: lgtm, size:M

#7661 feat: Add posthog continuous ai guide
  docs/docs.json
  docs/guides/overview.mdx
  docs/guides/posthog-github-continuous-ai.mdx
Labels: lgtm, size:L

#7778 bugfix: edit last input not selectable
  gui/src/components/mainInput/TipTapEditor/TipTapEditor.tsx
  packages/continue-sdk/package-lock.json
  packages/openai-adapters/package-lock.json
Labels: lgtm, size:S

#7786 chore: package lock updates
  core/package-lock.json
  extensions/vscode/package-lock.json
  gui/package-lock.json
Labels: lgtm, size:XS

#7722 fix: focus on the selected file for edit/apply when showing diffs
  extensions/vscode/src/diff/vertical/handler.ts
  extensions/vscode/src/diff/vertical/manager.ts
Labels: lgtm, size:M

#7813 fix: Remove redirect
  docs/docs.json
Labels: lgtm, size:XS

#7414 feat: global req
  core/config/load.ts
  core/config/profile/doLoadConfig.ts
  core/config/yaml/loadYaml.ts
  core/config/yaml/models.ts
  core/config/yaml/models.vitest.ts
  core/core.ts
  core/index.d.ts
  core/llm/streamChat.ts
  docs/reference.mdx
  extensions/vscode/src/webviewProtocol.ts
  gui/src/components/mainInput/Lump/EditBlockButton.tsx
  packages/config-yaml/src/converter.ts
  packages/config-yaml/src/load/merge.test.ts
  packages/config-yaml/src/load/merge.ts
  packages/config-yaml/src/load/unroll.ts
  packages/config-yaml/src/schemas/index.ts
  packages/openai-adapters/package-lock.json
  packages/openai-adapters/package.json
Labels: lgtm, size:XL

#7815 chore: config yaml 17
  packages/config-yaml/package.json
Labels: lgtm, size:XS

#7773 fix: remove empty lines from start/end in find and replace
  gui/src/pages/gui/ToolCallDiv/FindAndReplace.test.tsx
  gui/src/pages/gui/ToolCallDiv/FindAndReplace.tsx
  gui/src/util/clientTools/findAndReplaceUtils.test.ts
  gui/src/util/clientTools/findAndReplaceUtils.ts
Labels: lgtm, size:M

#7817 feat: add more robust context length validation
  core/llm/countTokens.ts
  extensions/cli/src/stream/streamChatResponse.ts
  extensions/cli/src/util/exponentialBackoff.ts
  extensions/cli/src/util/tokenizer.contextValidation.test.ts
  extensions/cli/src/util/tokenizer.test.ts
  extensions/cli/src/util/tokenizer.ts
Labels: lgtm, size:L

#7702 fix: ollama detect context length automatically
  core/llm/llms/Ollama.ts
  packages/llm-info/src/providers/os.ts
Labels: lgtm, size:XS

#7755 feat: use recommended models fn for tools
  core/llm/toolSupport.ts
  core/tools/index.ts
Labels: lgtm, size:XS

#7823 feat: display shortcuts for accept reject diff buttons
  gui/src/components/AcceptRejectDiffButtons.tsx
Labels: lgtm, size:XS

#7826 feat: add installation guides for mcp commands
  core/context/mcp/MCPConnection.ts
  core/context/mcp/MCPConnection.vitest.ts
  core/index.d.ts
  core/tools/mcpToolName.vitest.ts
  gui/src/pages/config/sections/ToolsSection.tsx
Labels: lgtm, size:M

#7825 chore: remove unused mcp section
  gui/src/pages/config/sections/McpSection.tsx
Labels: lgtm, size:L

#7842 fix: make config-yaml compatible with browser
  packages/config-yaml/src/interfaces/slugs.test.ts
  packages/config-yaml/src/interfaces/slugs.ts
Labels: lgtm, size:L

#7827 feat: add Mercury Apply endpoint support to Inception LLM
  core/core.ts
  core/edit/constants.ts
  core/edit/recursiveStream.ts
  core/edit/streamDiffLines.ts
  core/index.d.ts
  core/llm/llms/Inception.ts
  core/llm/templates/edit/gpt.ts
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/ApplyToFileHandler.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/DiffStreamHandler.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/InlineEditPanel.kt
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/types.kt
  extensions/vscode/src/apply/ApplyManager.ts
  extensions/vscode/src/commands.ts
  extensions/vscode/src/diff/vertical/manager.ts
  extensions/vscode/src/extension/VsCodeMessenger.ts
  extensions/vscode/src/quickEdit/QuickEditQuickPick.ts
  packages/config-yaml/package-lock.json
  packages/continue-sdk/package-lock.json
  packages/openai-adapters/src/apis/Inception.ts
Labels: size:L

#7776 feat: next edit char-level diff
  core/codeRenderer/CodeRenderer.ts
  core/llm/index.ts
  extensions/vscode/src/activation/NextEditWindowManager.ts
  extensions/vscode/src/autocomplete/__tests__/ContinueCompletionProvider.vitest.ts
  extensions/vscode/src/autocomplete/completionProvider.ts
Labels: size:XL

#7816 feat: revamp efficient file search and support fuzzy matching
  extensions/cli/package-lock.json
  extensions/cli/package.json
  extensions/cli/src/e2e/home-directory-warning.test.ts
  extensions/cli/src/services/FileIndexService.test.ts
  extensions/cli/src/services/FileIndexService.ts
  extensions/cli/src/ui/FileSearchUI.tsx
  extensions/cli/src/ui/IntroMessage.tsx
  extensions/cli/src/ui/UserInput.tsx
  extensions/cli/src/ui/__tests__/UserInput.missingFile.test.tsx
Labels: lgtm, size:XXL

#7793 chore: default to org agent when onboarding
  extensions/cli/src/auth/orgSelection.test.ts
  extensions/cli/src/auth/orgSelection.ts
  extensions/cli/src/auth/workos.helpers.ts
  extensions/cli/src/auth/workos.ts
  extensions/cli/src/commands/chat.ts
  extensions/cli/src/config.ts
  extensions/cli/src/configLoader.ts
  extensions/cli/src/onboarding.ts
Labels: size:L

#7860 feat: split large blocks of chat history to reduce flickering
  extensions/cli/src/ui/components/MemoizedMessage.tsx
  extensions/cli/src/ui/components/StaticChatContent.tsx
  extensions/cli/src/ui/hooks/useMessageRenderer.tsx
  extensions/cli/src/ui/utils/historySplitting.test.ts
  extensions/cli/src/ui/utils/historySplitting.ts
  extensions/cli/src/ui/utils/messageSplitting.test.ts
  extensions/cli/src/ui/utils/messageSplitting.ts
Labels: lgtm, size:XL

#7867 chore: version bumps
  extensions/intellij/gradle.properties
  extensions/vscode/package.json
Labels: size:XS

#7865 fix: cn auto compact if necessary before LLM api call
  extensions/cli/src/stream/streamChatResponse.ts
Labels: lgtm, size:S

#7694 feat: show remote sessions in cn ls
  .vscode/launch.json
  .vscode/tasks.json
  actions/general-review/action.yml
  core/config/yaml/yamlToContinueConfig.ts
  core/control-plane/client.ts
  core/core.ts
  core/index.d.ts
  core/protocol/core.ts
  core/protocol/passThrough.ts
  core/util/history.ts
  extensions/cli/build.mjs
  extensions/cli/src/auth/workos.ts
  extensions/cli/src/commands/commands.integration.test.ts
  extensions/cli/src/commands/commands.ts
  extensions/cli/src/commands/ls.test.ts
  extensions/cli/src/commands/ls.ts
  extensions/cli/src/index.ts
  extensions/cli/src/session.ts
  extensions/cli/src/slashCommands.remote.test.ts
  extensions/cli/src/slashCommands.test.ts
  extensions/cli/src/slashCommands.ts
  extensions/cli/src/test-helpers/cli-helpers.ts
  extensions/cli/src/ui/DiffViewer.tsx
  extensions/cli/src/ui/SessionSelector.test.tsx
  extensions/cli/src/ui/SessionSelector.tsx
  extensions/cli/src/ui/TUIChat.tsx
  extensions/cli/src/ui/UserInput.tsx
  extensions/cli/src/ui/__tests__/TUIChat.slashCommands.test.tsx
  extensions/cli/src/ui/components/ScreenContent.tsx
  extensions/cli/src/ui/components/SessionSelectorWithLoading.tsx
  extensions/cli/src/ui/context/NavigationContext.tsx
  extensions/cli/src/ui/hooks/useChat.helpers.ts
  extensions/cli/src/ui/hooks/useChat.remote.helpers.ts
  extensions/cli/src/ui/hooks/useChat.ts
  extensions/cli/src/ui/hooks/useChat.types.ts
  extensions/cli/src/util/fileWatcher.test.ts
  extensions/cli/src/util/fileWatcher.ts
  gui/src/components/History/HistoryTableRow.tsx
  gui/src/components/History/index.tsx
  gui/src/components/History/util.ts
  gui/src/context/MockIdeMessenger.ts
  gui/src/pages/gui/Chat.tsx
  gui/src/redux/slices/sessionSlice.ts
  gui/src/redux/thunks/session.ts
  packages/openai-adapters/package-lock.json
Labels: lgtm, size:XXL

#7884 feat: --id flag for cn serve
  extensions/cli/docs/storage-sync.md
  extensions/cli/src/commands/serve.ts
  extensions/cli/src/index.ts
  extensions/cli/src/services/StorageSyncService.test.ts
  extensions/cli/src/services/StorageSyncService.ts
  extensions/cli/src/services/index.ts
  extensions/cli/src/services/types.ts
  extensions/cli/src/session.ts
  extensions/cli/src/util/git.ts
Labels: size:XL

#7872 fix: HOTFIX r.map is not a function
  gui/src/pages/gui/ToolCallDiv/FindAndReplace.tsx
Labels: lgtm, size:XS

#7851 fix: uniform codeblock border
  gui/src/components/UnifiedTerminal/UnifiedTerminal.tsx
Labels: lgtm, size:XS

#7875 feat: restore trimmed/whitespace search and replace fallbacks
  core/config/types.ts
  core/edit/searchAndReplace/executeFindAndReplace.vitest.ts
  core/edit/searchAndReplace/findAndReplaceUtils.ts
  core/edit/searchAndReplace/findAndReplaceUtils.vitest.ts
  core/edit/searchAndReplace/findSearchMatch.ts
  core/edit/searchAndReplace/findSearchMatch.vitest.ts
  core/edit/searchAndReplace/findSearchMatches.test.ts
  core/edit/searchAndReplace/multiEdit.vitest.ts
  core/edit/searchAndReplace/multiEditValidation.ts
  core/edit/searchAndReplace/performReplace.ts
  core/index.d.ts
  core/indexing/ignore.ts
  core/tools/definitions/multiEdit.ts
  core/util/errors.ts
  extensions/cli/src/stream/streamChatResponse.helpers.ts
  extensions/cli/src/telemetry/telemetryService.ts
  extensions/cli/src/tools/edit.test.ts
  extensions/cli/src/tools/edit.ts
  extensions/cli/src/tools/index.tsx
  extensions/cli/src/tools/multiEdit.test.ts
  extensions/cli/src/tools/multiEdit.ts
  extensions/cli/src/tools/preprocess.test.ts
  extensions/cli/src/tools/searchAndReplace/index.ts
  extensions/cli/src/tools/searchAndReplace/parseArgs.ts
  extensions/cli/src/tools/searchAndReplace/parseBlock.ts
  gui/src/components/gui/ErrorStepContainer.tsx
  gui/src/pages/gui/ToolCallDiv/FindAndReplace.test.tsx
  gui/src/pages/gui/ToolCallDiv/FindAndReplace.tsx
  gui/src/redux/thunks/callToolById.ts
  gui/src/redux/thunks/cancelToolCall.ts
  gui/src/redux/thunks/streamResponse_toolCalls.test.ts
  gui/src/util/clientTools/callClientTool.ts
  gui/src/util/clientTools/findAndReplaceUtils.test.ts
  gui/src/util/clientTools/findAndReplaceUtils.ts
  gui/src/util/clientTools/multiEditImpl.test.ts
  gui/src/util/clientTools/multiEditImpl.ts
  gui/src/util/clientTools/singleFindAndReplaceImpl.test.ts
  gui/src/util/clientTools/singleFindAndReplaceImpl.ts
Labels: lgtm, size:XXL

#7205 Fix image drop from main editor
  .vscode/launch.json
  .vscode/tasks.json
  core/protocol/ide.ts
  extensions/vscode/src/extension/VsCodeMessenger.ts
  gui/src/components/mainInput/TipTapEditor/TipTapEditor.tsx
  gui/src/components/mainInput/TipTapEditor/components/DragOverlay.tsx
  gui/src/components/mainInput/TipTapEditor/components/StyledComponents.ts
  gui/src/components/mainInput/TipTapEditor/utils/editorConfig.ts
  gui/src/components/mainInput/TipTapEditor/utils/imageUtils.ts
Labels: lgtm, size:L

#7651 feat(oauth): use asExternalUrl to get the correct callback
  core/config/types.ts
  core/context/mcp/MCPOauth.ts
  core/context/mcp/MCPOauth.vitest.ts
  core/index.d.ts
  extensions/vscode/src/VsCodeIde.ts
Labels: lgtm, size:L

#7901 fix: Update sambanova models
  core/llm/llms/SambaNova.ts
  core/llm/toolSupport.ts
  docs/customize/model-providers/more/SambaNova.mdx
  gui/src/pages/AddNewModel/configs/models.ts
  gui/src/pages/AddNewModel/configs/providers.ts
Labels: lgtm, size:L

#7906 fix: infos in mcp server status tests
  core/context/mcp/MCPOauth.vitest.ts
Labels: size:XS

#6802 feat: expose legacy /share command to VS Code UI
  core/commands/slash/built-in-legacy/share.ts
  core/core.ts
  core/protocol/core.ts
  core/protocol/ideWebview.ts
  core/util/historyUtils.ts
  extensions/vscode/package.json
  extensions/vscode/src/commands.ts
  extensions/vscode/src/extension/VsCodeMessenger.ts
  gui/src/components/History/HistoryTableRow.tsx
  gui/src/util/index.ts
Labels: lgtm, size:L

#7717 feat: support for AGENTS.md
  core/config/markdown/loadMarkdownRules.ts
  core/core.ts
  core/index.d.ts
  core/llm/rules/rules-utils.ts
  gui/src/components/mainInput/belowMainInput/RulesPeek.tsx
  gui/src/pages/config/sections/RulesSection.tsx
Labels: lgtm, size:L

#7939 fix: inline --rule improvements and fix msg queue behavior
  extensions/cli/src/commands/serve.helpers.ts
  extensions/cli/src/commands/serve.ts
  extensions/cli/src/hubLoader.test.ts
  extensions/cli/src/hubLoader.ts
  extensions/cli/src/stream/messageQueue.test.ts
  extensions/cli/src/stream/messageQueue.ts
  extensions/cli/src/ui/UserInput.tsx
  extensions/cli/src/ui/hooks/useChat.ts
Labels: size:L

#7929 Refactor session snapshot handling to use getCompleteStateSnapshot
  .github/workflows/continue-detailed-review.yaml
  .github/workflows/continue-general-review.yaml
  extensions/cli/src/commands/serve.ts
  extensions/cli/src/services/StorageSyncService.test.ts
  extensions/cli/src/services/StorageSyncService.ts
  extensions/cli/src/session.ts
Labels: size:M

#7830 feat: better mcp connection status
  core/context/mcp/MCPConnection.ts
  core/context/mcp/MCPManagerSingleton.ts
  core/core.ts
  core/protocol/core.ts
  core/protocol/passThrough.ts
  gui/src/pages/config/hooks/useToolPolicies.ts
  gui/src/pages/config/sections/ToolsSection.tsx
Labels: lgtm, size:L

#7943 fix: close the model select dropdown automatically
  gui/src/components/modelSelection/ModelSelect.tsx
Labels: lgtm, size:S

#7938 fix: HOTFIX :ambulance: Fix crypto error
  core/context/mcp/MCPOauth.ts
  core/llm/utils/getSecureID.test.ts
  core/llm/utils/getSecureID.ts
  gui/src/hooks/useLLMLog.ts
  packages/openai-adapters/src/apis/Bedrock.ts
Labels: lgtm, size:M, hotfix

#7809 ✨ add CometAPI as Model Provider
  core/llm/llms/CometAPI.ts
  core/llm/llms/OpenAI-compatible-core.vitest.ts
  core/llm/llms/index.ts
  gui/public/logos/cometapi.png
  gui/src/pages/AddNewModel/configs/models.ts
  gui/src/pages/AddNewModel/configs/providers.ts
  packages/llm-info/src/index.ts
  packages/llm-info/src/providers/cometapi.ts
  packages/openai-adapters/src/apis/CometAPI.ts
  packages/openai-adapters/src/index.ts
  packages/openai-adapters/src/types.ts
Labels: lgtm, size:XXL

#7925 feat: grok model updates
  core/llm/llms/xAI.ts
  core/llm/toolSupport.test.ts
  core/llm/toolSupport.ts
  docs/customization/models.mdx
  docs/customize/deep-dives/model-capabilities.mdx
  docs/customize/model-providers/more/xAI.mdx
  gui/src/pages/AddNewModel/configs/models.ts
  gui/src/pages/AddNewModel/configs/providers.ts
  packages/llm-info/package.json
  packages/llm-info/src/providers/xAI.ts
Labels: lgtm, size:L

#7967 Update gradle.properties
  extensions/intellij/gradle.properties
Labels: size:XS

#7968 Delete .github/workflows/respond-to-cubic.yaml
  .github/workflows/respond-to-cubic.yaml
Labels: size:L

#7888 feat(cli): enhance /init command to create custom slash command
  core/config/markdown/utils.ts
  extensions/cli/src/commands/init.ts
Labels: size:M

#7960 fix: update MermaidBlock styles for improved rendering and add foreignObject
  gui/src/components/StyledMarkdownPreview/MermaidBlock.tsx
  gui/src/components/StyledMarkdownPreview/markdown.css
Labels: size:XS

#7983 feat: .continue/environment.json
  .continue/environment.json
  .husky/pre-commit
Labels: lgtm, size:XS

#7977 feat: make ToolCallStatusMessage.tsx clickable
  gui/src/pages/gui/ToolCallDiv/ToolCallDisplay.tsx
Labels: lgtm, size:S

#7664 docs: initial prompts changes
  docs/customization/overview.mdx
  docs/customization/prompts.mdx
  docs/customize/deep-dives/configuration.mdx
  docs/customize/deep-dives/prompts.mdx
  docs/customize/deep-dives/rules.mdx
  docs/customize/deep-dives/slash-commands.mdx
  docs/customize/model-roles/edit.mdx
  docs/customize/model-roles/embeddings.mdx
  docs/customize/model-roles/intro.mdx
  docs/customize/model-roles/reranking.mdx
  docs/customize/overview.mdx
  docs/features/chat/how-it-works.mdx
  docs/getting-started/extensions.mdx
  docs/getting-started/overview.mdx
  docs/getting-started/quick-start.mdx
  docs/guides/codebase-documentation-awareness.mdx
  docs/hub/blocks/block-types.mdx
  docs/hub/introduction.mdx
  docs/hub/sharing.mdx
  docs/reference.mdx
  docs/reference/json-reference.mdx
Labels: lgtm, size:L

#7984 feat: handle environment.json file in cn serve
  extensions/cli/src/commands/serve.ts
  extensions/cli/src/environment/environmentHandler.ts
Labels: size:L

#7443 feat: :sparkles: CLI: Add aws credentials onboarding
  .vscode/launch.json
  extensions/cli/spec/onboarding.md
  extensions/cli/src/onboarding.test.ts
  extensions/cli/src/onboarding.ts
Labels: lgtm, size:L

#7976 fix: Simplify review bot, remove detailed review, keep general review only
  .github/pull_request_template.md
  .github/workflows/continue-detailed-review.yaml
  .github/workflows/pr-checks.yaml
  actions/README.md
  actions/detailed-review/action.yml
  actions/detailed-review/annotate-diff.js
  actions/detailed-review/annotate-diff.test.js
  actions/detailed-review/package.json
  actions/general-review/action.yml
Labels: lgtm, size:XXL

#7956 feat: support standard MCP JSON formats
  core/config/load.ts
  core/config/loadLocalAssistants.ts
  core/config/yaml/loadYaml.ts
  core/config/yaml/yamlToContinueConfig.ts
  core/context/mcp/MCPConnection.ts
  core/context/mcp/MCPConnection.vitest.ts
  core/context/mcp/MCPManagerSingleton.ts
  core/context/mcp/MCPManagerSingleton.vitest.ts
  core/context/mcp/MCPOauth.ts
  core/context/mcp/MCPOauth.vitest.ts
  core/context/mcp/json/loadJsonMcpConfigs.ts
  core/core.ts
  core/index.d.ts
  core/package-lock.json
  core/protocol/core.ts
  core/tools/mcpToolName.vitest.ts
  docs/reference.mdx
  extensions/cli/package-lock.json
  extensions/cli/src/services/MCPService.ts
  extensions/cli/src/ui/MCPSelector.tsx
  extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt
  gui/src/pages/config/sections/ToolsSection.tsx
  manual-testing-sandbox/claude_desktop_config.json
  packages/config-yaml/package-lock.json
  packages/config-yaml/package.json
  packages/config-yaml/src/browser.ts
  packages/config-yaml/src/schemas/index.ts
  packages/config-yaml/src/schemas/mcp/convertJson.test.ts
  packages/config-yaml/src/schemas/mcp/convertJson.ts
  packages/config-yaml/src/schemas/mcp/index.ts
  packages/config-yaml/src/schemas/mcp/json.ts
  packages/continue-sdk/package-lock.json
  packages/llm-info/package-lock.json
Labels: lgtm, size:XXL

#8002 fix: json mcp loading
  core/context/mcp/json/loadJsonMcpConfigs.ts
  packages/config-yaml/src/schemas/mcp/json.ts
Labels: lgtm, size:M

#7998 fix: edit tool prompt updates to encourage multi edits to avoid linting effects
  core/tools/definitions/multiEdit.ts
  extensions/cli/src/tools/multiEdit.ts
Labels: lgtm, size:S

#7999 feat: Add --id option to connect to existing remote agents via tunnel
  extensions/cli/src/commands/remote.test.ts
  extensions/cli/src/commands/remote.ts
  extensions/cli/src/index.ts
Labels: size:L

#8034 feat: Add docs contributing guide
  docs/CONTRIBUTING.mdx
  docs/docs.json
Labels: size:L
